// Code generated by github.com/go-mc/packetizer; DO NOT EDIT.

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/net/packet"
)

func (c *LoginCookieRequest) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Key).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c LoginCookieRequest) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Key).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *LoginCustomQuery) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.MessageID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Identifier)(&c.Channel).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.ByteArray)(&c.Data).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c LoginCustomQuery) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.MessageID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Identifier)(&c.Channel).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.ByteArray)(&c.Data).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *LoginHello) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.String)(&c.ServerID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.ByteArray)(&c.PublicKey).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.ByteArray)(&c.VerifyToken).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Boolean)(&c.ShouldAuthenticate).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c LoginHello) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.String)(&c.ServerID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.ByteArray)(&c.PublicKey).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.ByteArray)(&c.VerifyToken).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Boolean)(&c.ShouldAuthenticate).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *LoginLoginCompression) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.Threshold).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c LoginLoginCompression) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.Threshold).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *LoginLoginDisconnect) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (&c.Reason).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c LoginLoginDisconnect) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (&c.Reason).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *LoginLoginFinished) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.UUID)(&c.UUID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.String)(&c.Name).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = packet.Array(&c.Properties).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c LoginLoginFinished) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.UUID)(&c.UUID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.String)(&c.Name).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = packet.Array(&c.Properties).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
