// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// UpdateStructureBlock represents the Serverbound UpdateStructureBlock packet.

type UpdateStructureBlock struct {
	// Bitfield - see protocol spec for bit layout
	Location int32
	Action   int32 `mc:"VarInt"`
	Mode     int32 `mc:"VarInt"`
	// TODO: Implement pstring type
	Name     interface{}
	OffsetX  int8
	OffsetY  int8
	OffsetZ  int8
	SizeX    int8
	SizeY    int8
	SizeZ    int8
	Mirror   int32 `mc:"VarInt"`
	Rotation int32 `mc:"VarInt"`
	// TODO: Implement pstring type
	Metadata  interface{}
	Integrity float32
	Seed      int32 `mc:"VarInt"`
	// TODO: Implement mapper type
	Flags interface{}
}

// PacketID returns the packet ID for this packet.
func (*UpdateStructureBlock) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundUpdateStructureBlock
}

// ReadFrom reads the packet data from the reader.
func (p *UpdateStructureBlock) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.Int)(&p.Location).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var action pk.VarInt
	temp, err = action.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Action = int32(action)

	var mode pk.VarInt
	temp, err = mode.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Mode = int32(mode)

	// TODO: Read Name

	var offsetX int8
	temp, err = (*pk.Byte)(&offsetX).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.OffsetX = offsetX

	var offsetY int8
	temp, err = (*pk.Byte)(&offsetY).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.OffsetY = offsetY

	var offsetZ int8
	temp, err = (*pk.Byte)(&offsetZ).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.OffsetZ = offsetZ

	var sizeX int8
	temp, err = (*pk.Byte)(&sizeX).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.SizeX = sizeX

	var sizeY int8
	temp, err = (*pk.Byte)(&sizeY).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.SizeY = sizeY

	var sizeZ int8
	temp, err = (*pk.Byte)(&sizeZ).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.SizeZ = sizeZ

	var mirror pk.VarInt
	temp, err = mirror.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Mirror = int32(mirror)

	var rotation pk.VarInt
	temp, err = rotation.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Rotation = int32(rotation)

	// TODO: Read Metadata

	temp, err = (*pk.Float)(&p.Integrity).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var seed pk.VarInt
	temp, err = seed.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Seed = int32(seed)

	// TODO: Read Flags

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p UpdateStructureBlock) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Int(p.Location).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.Action).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.Mode).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Name

	temp, err = pk.Byte(p.OffsetX).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.OffsetY).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.OffsetZ).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.SizeX).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.SizeY).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.SizeZ).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.Mirror).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.Rotation).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Metadata

	temp, err = pk.Float(p.Integrity).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.Seed).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Flags

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundUpdateStructureBlock, func() ServerboundPacket {
		return &UpdateStructureBlock{}
	})
}
