//go:build ignore
// +build ignore

// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// EditBook represents the Serverbound EditBook packet.

type EditBook struct {
	Hand  int32 `mc:"VarInt"`
	Pages []string
	Title *string
}

// PacketID returns the packet ID for this packet.
func (*EditBook) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundEditBook
}

// ReadFrom reads the packet data from the reader.
func (p *EditBook) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var hand pk.VarInt
	temp, err = hand.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Hand = int32(hand)

	var pagesCount pk.VarInt
	temp, err = pagesCount.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Pages = make([]string, pagesCount)
	for i := 0; i < int(pagesCount); i++ {
		var elem pk.String
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.Pages[i] = string(elem)
	}

	var hasTitle pk.Boolean
	temp, err = hasTitle.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if hasTitle {
		var val string
		var elem pk.String
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = string(elem)
		p.Title = &val
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p EditBook) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.Hand).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(len(p.Pages)).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	for i := range p.Pages {
		temp, err = pk.String(p.Pages[i]).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	if p.Title != nil {
		temp, err = pk.Boolean(true).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		temp, err = pk.String(*p.Title).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	} else {
		temp, err = pk.Boolean(false).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundEditBook, func() ServerboundPacket {
		return &EditBook{}
	})
}
