// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// UpdateCommandBlock represents the Serverbound UpdateCommandBlock packet.

type UpdateCommandBlock struct {
	// Bitfield - see protocol spec for bit layout
	Location int32
	// TODO: Implement pstring type
	Command interface{}
	Mode    int32 `mc:"VarInt"`
	Flags   uint8
}

// PacketID returns the packet ID for this packet.
func (*UpdateCommandBlock) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundUpdateCommandBlock
}

// ReadFrom reads the packet data from the reader.
func (p *UpdateCommandBlock) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.Int)(&p.Location).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Read Command

	var mode pk.VarInt
	temp, err = mode.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Mode = int32(mode)

	var flags pk.UnsignedByte
	temp, err = flags.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Flags = uint8(flags)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p UpdateCommandBlock) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Int(p.Location).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Command

	temp, err = pk.VarInt(p.Mode).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.UnsignedByte(p.Flags).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundUpdateCommandBlock, func() ServerboundPacket {
		return &UpdateCommandBlock{}
	})
}
