// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// ChangeGamemode represents the Serverbound ChangeGamemode packet.

type ChangeGamemode struct {
	// TODO: Implement mapper type
	Mode interface{}
}

// PacketID returns the packet ID for this packet.
func (*ChangeGamemode) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundChangeGamemode
}

// ReadFrom reads the packet data from the reader.
func (p *ChangeGamemode) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Read Mode

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p ChangeGamemode) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Write Mode

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundChangeGamemode, func() ServerboundPacket {
		return &ChangeGamemode{}
	})
}
