//go:build ignore
// +build ignore

// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// SetTestBlock represents the Serverbound SetTestBlock packet.

type SetTestBlock struct {
	// Bitfield - see protocol spec for bit layout
	Position int32
	Mode     int32 `mc:"VarInt"`
	// TODO: Implement pstring type
	Message interface{}
}

// PacketID returns the packet ID for this packet.
func (*SetTestBlock) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundSetTestBlock
}

// ReadFrom reads the packet data from the reader.
func (p *SetTestBlock) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.Int)(&p.Position).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var mode pk.VarInt
	temp, err = mode.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Mode = int32(mode)

	// TODO: Read Message

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p SetTestBlock) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Int(p.Position).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.Mode).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Message

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundSetTestBlock, func() ServerboundPacket {
		return &SetTestBlock{}
	})
}
