// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// SetBeaconEffect represents the Serverbound SetBeaconEffect packet.

type SetBeaconEffect struct {
	PrimaryEffect   *int32
	SecondaryEffect *int32
}

// PacketID returns the packet ID for this packet.
func (*SetBeaconEffect) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundSetBeaconEffect
}

// ReadFrom reads the packet data from the reader.
func (p *SetBeaconEffect) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var hasPrimaryEffect pk.Boolean
	temp, err = hasPrimaryEffect.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if hasPrimaryEffect {
		var val int32
		var elem pk.VarInt
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = int32(elem)
		p.PrimaryEffect = &val
	}

	var hasSecondaryEffect pk.Boolean
	temp, err = hasSecondaryEffect.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if hasSecondaryEffect {
		var val int32
		var elem pk.VarInt
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = int32(elem)
		p.SecondaryEffect = &val
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p SetBeaconEffect) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	if p.PrimaryEffect != nil {
		temp, err = pk.Boolean(true).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		temp, err = pk.VarInt(*p.PrimaryEffect).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	} else {
		temp, err = pk.Boolean(false).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	if p.SecondaryEffect != nil {
		temp, err = pk.Boolean(true).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		temp, err = pk.VarInt(*p.SecondaryEffect).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	} else {
		temp, err = pk.Boolean(false).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundSetBeaconEffect, func() ServerboundPacket {
		return &SetBeaconEffect{}
	})
}
