//go:build ignore
// +build ignore

// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// TabComplete represents the Serverbound TabComplete packet.

type TabComplete struct {
	TransactionId int32 `mc:"VarInt"`
	// TODO: Implement pstring type
	Text interface{}
}

// PacketID returns the packet ID for this packet.
func (*TabComplete) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundTabComplete
}

// ReadFrom reads the packet data from the reader.
func (p *TabComplete) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var transactionId pk.VarInt
	temp, err = transactionId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.TransactionId = int32(transactionId)

	// TODO: Read Text

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p TabComplete) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.TransactionId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Text

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundTabComplete, func() ServerboundPacket {
		return &TabComplete{}
	})
}
