//go:build ignore
// +build ignore

// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// Spectate represents the Serverbound Spectate packet.

type Spectate struct {
	Target pk.UUID
}

// PacketID returns the packet ID for this packet.
func (*Spectate) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundSpectate
}

// ReadFrom reads the packet data from the reader.
func (p *Spectate) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.UUID)(&p.Target).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Spectate) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = p.Target.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundSpectate, func() ServerboundPacket {
		return &Spectate{}
	})
}
