//go:build ignore
// +build ignore

// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// UpdateJigsawBlock represents the Serverbound UpdateJigsawBlock packet.

type UpdateJigsawBlock struct {
	// Bitfield - see protocol spec for bit layout
	Location int32
	// TODO: Implement pstring type
	Name interface{}
	// TODO: Implement pstring type
	Target interface{}
	// TODO: Implement pstring type
	Pool interface{}
	// TODO: Implement pstring type
	FinalState interface{}
	// TODO: Implement pstring type
	JointType         interface{}
	SelectionPriority int32 `mc:"VarInt"`
	PlacementPriority int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*UpdateJigsawBlock) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundUpdateJigsawBlock
}

// ReadFrom reads the packet data from the reader.
func (p *UpdateJigsawBlock) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.Int)(&p.Location).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Read Name

	// TODO: Read Target

	// TODO: Read Pool

	// TODO: Read FinalState

	// TODO: Read JointType

	var selectionPriority pk.VarInt
	temp, err = selectionPriority.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.SelectionPriority = int32(selectionPriority)

	var placementPriority pk.VarInt
	temp, err = placementPriority.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.PlacementPriority = int32(placementPriority)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p UpdateJigsawBlock) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Int(p.Location).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Name

	// TODO: Write Target

	// TODO: Write Pool

	// TODO: Write FinalState

	// TODO: Write JointType

	temp, err = pk.VarInt(p.SelectionPriority).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.PlacementPriority).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundUpdateJigsawBlock, func() ServerboundPacket {
		return &UpdateJigsawBlock{}
	})
}
