// Code generated by enhanced-generator; DO NOT EDIT.
package server

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type EditBook struct {
	Hand  int32 `mc:"VarInt"`
	Pages []interface{}
	Title interface{}
}

func (*EditBook) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundPacketID(23)
}

// ReadFrom is a stub (not implemented)
func (p *EditBook) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p EditBook) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ServerboundPacketID(23), func() ServerboundPacket { return &EditBook{} })
}
