// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// PickItemFromEntity represents the Serverbound PickItemFromEntity packet.

type PickItemFromEntity struct {
	EntityId    int32 `mc:"VarInt"`
	IncludeData bool
}

// PacketID returns the packet ID for this packet.
func (*PickItemFromEntity) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundPickItemFromEntity
}

// ReadFrom reads the packet data from the reader.
func (p *PickItemFromEntity) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var entityId pk.VarInt
	temp, err = entityId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.EntityId = int32(entityId)

	var includeData pk.Boolean
	temp, err = includeData.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.IncludeData = bool(includeData)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p PickItemFromEntity) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.EntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Boolean(p.IncludeData).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundPickItemFromEntity, func() ServerboundPacket {
		return &PickItemFromEntity{}
	})
}
