// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// Look represents the Serverbound Look packet.

type Look struct {
	Yaw   float32
	Pitch float32
	// Bitflags
	Flags uint8
}

// PacketID returns the packet ID for this packet.
func (*Look) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundLook
}

// ReadFrom reads the packet data from the reader.
func (p *Look) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.Float)(&p.Yaw).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&p.Pitch).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var flags pk.UnsignedByte
	temp, err = flags.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Flags = uint8(flags)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Look) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Float(p.Yaw).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.Pitch).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.UnsignedByte(p.Flags).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundLook, func() ServerboundPacket {
		return &Look{}
	})
}
