// Code generated by enhanced-generator; DO NOT EDIT.
package server

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type UpdateCommandBlockMinecart struct {
	EntityId    int32  `mc:"VarInt"`
	Command     string `mc:"String"`
	TrackOutput bool   `mc:"Boolean"`
}

func (*UpdateCommandBlockMinecart) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundPacketID(0)
}

// ReadFrom is a stub (not implemented)
func (p *UpdateCommandBlockMinecart) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p UpdateCommandBlockMinecart) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ServerboundPacketID(0), func() ServerboundPacket { return &UpdateCommandBlockMinecart{} })
}
