// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	"fmt"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// EntityAction represents the Serverbound EntityAction packet.

type EntityAction struct {
	EntityId int32 `mc:"VarInt"`
	// Mapper to string
	ActionId  string
	JumpBoost int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*EntityAction) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundEntityAction
}

// ReadFrom reads the packet data from the reader.
func (p *EntityAction) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var entityId pk.VarInt
	temp, err = entityId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.EntityId = int32(entityId)

	var mapperVal pk.VarInt
	temp, err = mapperVal.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	switch mapperVal {
	case 3:
		p.ActionId = "start_horse_jump"
	case 4:
		p.ActionId = "stop_horse_jump"
	case 5:
		p.ActionId = "open_vehicle_inventory"
	case 6:
		p.ActionId = "start_elytra_flying"
	case 0:
		p.ActionId = "leave_bed"
	case 1:
		p.ActionId = "start_sprinting"
	case 2:
		p.ActionId = "stop_sprinting"
	default:
		return n, fmt.Errorf("unknown mapper value %d for ActionId", mapperVal)
	}

	var jumpBoost pk.VarInt
	temp, err = jumpBoost.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.JumpBoost = int32(jumpBoost)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p EntityAction) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.EntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	switch p.ActionId {
	case "start_horse_jump":
		temp, err = pk.VarInt(3).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	case "stop_horse_jump":
		temp, err = pk.VarInt(4).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	case "open_vehicle_inventory":
		temp, err = pk.VarInt(5).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	case "start_elytra_flying":
		temp, err = pk.VarInt(6).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	case "leave_bed":
		temp, err = pk.VarInt(0).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	case "start_sprinting":
		temp, err = pk.VarInt(1).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	case "stop_sprinting":
		temp, err = pk.VarInt(2).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unknown ActionId value %v", p.ActionId)
	}

	temp, err = pk.VarInt(p.JumpBoost).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundEntityAction, func() ServerboundPacket {
		return &EntityAction{}
	})
}
