// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// NameItem represents the Serverbound NameItem packet.

type NameItem struct {
	Name string `mc:"String"`
}

// PacketID returns the packet ID for this packet.
func (*NameItem) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundNameItem
}

// ReadFrom reads the packet data from the reader.
func (p *NameItem) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var name pk.String
	temp, err = name.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Name = string(name)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p NameItem) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.String(p.Name).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundNameItem, func() ServerboundPacket {
		return &NameItem{}
	})
}
