// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// PickItemFromBlock represents the Serverbound PickItemFromBlock packet.

type PickItemFromBlock struct {
	// Bitfield - see protocol spec for bit layout
	Position    int32
	IncludeData bool
}

// PacketID returns the packet ID for this packet.
func (*PickItemFromBlock) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundPickItemFromBlock
}

// ReadFrom reads the packet data from the reader.
func (p *PickItemFromBlock) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.Int)(&p.Position).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var includeData pk.Boolean
	temp, err = includeData.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.IncludeData = bool(includeData)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p PickItemFromBlock) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Int(p.Position).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Boolean(p.IncludeData).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundPickItemFromBlock, func() ServerboundPacket {
		return &PickItemFromBlock{}
	})
}
