// Code generated by enhanced-generator; DO NOT EDIT.
package server

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type TestInstanceBlockAction struct {
	Pos    interface{}
	Action int32 `mc:"VarInt"`
	Data   interface{}
}

func (*TestInstanceBlockAction) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundPacketID(62)
}

// ReadFrom is a stub (not implemented)
func (p *TestInstanceBlockAction) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p TestInstanceBlockAction) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ServerboundPacketID(62), func() ServerboundPacket { return &TestInstanceBlockAction{} })
}
