// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	"fmt"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// ChangeGamemode represents the Serverbound ChangeGamemode packet.

type ChangeGamemode struct {
	// Mapper to string
	Mode string
}

// PacketID returns the packet ID for this packet.
func (*ChangeGamemode) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundChangeGamemode
}

// ReadFrom reads the packet data from the reader.
func (p *ChangeGamemode) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var mapperVal pk.VarInt
	temp, err = mapperVal.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	switch mapperVal {
	case 2:
		p.Mode = "adventure"
	case 3:
		p.Mode = "spectator"
	case 0:
		p.Mode = "survival"
	case 1:
		p.Mode = "creative"
	default:
		return n, fmt.Errorf("unknown mapper value %d for Mode", mapperVal)
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p ChangeGamemode) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	switch p.Mode {
	case "adventure":
		temp, err = pk.VarInt(2).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	case "spectator":
		temp, err = pk.VarInt(3).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	case "survival":
		temp, err = pk.VarInt(0).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	case "creative":
		temp, err = pk.VarInt(1).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unknown Mode value %v", p.Mode)
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundChangeGamemode, func() ServerboundPacket {
		return &ChangeGamemode{}
	})
}
