// Code generated by enhanced-generator; DO NOT EDIT.
package server

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type PickItemFromBlock struct {
	Position    interface{}
	IncludeData bool `mc:"Boolean"`
}

func (*PickItemFromBlock) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundPacketID(35)
}

// ReadFrom is a stub (not implemented)
func (p *PickItemFromBlock) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p PickItemFromBlock) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ServerboundPacketID(35), func() ServerboundPacket { return &PickItemFromBlock{} })
}
