// Code generated by enhanced-generator; DO NOT EDIT.
package server

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type ChatMessage struct {
	Message      string `mc:"String"`
	Timestamp    int64  `mc:"Long"`
	Salt         int64  `mc:"Long"`
	Signature    interface{}
	Offset       int32 `mc:"VarInt"`
	Acknowledged interface{}
	Checksum     int8 `mc:"Byte"`
}

func (*ChatMessage) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundPacketID(0)
}

// ReadFrom is a stub (not implemented)
func (p *ChatMessage) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p ChatMessage) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ServerboundPacketID(0), func() ServerboundPacket { return &ChatMessage{} })
}
