// Code generated by enhanced-generator; DO NOT EDIT.
package server

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type BlockPlace struct {
	Hand           int32 `mc:"VarInt"`
	Location       interface{}
	Direction      int32   `mc:"VarInt"`
	CursorX        float32 `mc:"Float"`
	CursorY        float32 `mc:"Float"`
	CursorZ        float32 `mc:"Float"`
	InsideBlock    bool    `mc:"Boolean"`
	WorldBorderHit bool    `mc:"Boolean"`
	Sequence       int32   `mc:"VarInt"`
}

func (*BlockPlace) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundPacketID(0)
}

// ReadFrom is a stub (not implemented)
func (p *BlockPlace) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p BlockPlace) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ServerboundPacketID(0), func() ServerboundPacket { return &BlockPlace{} })
}
