// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// UpdateCommandBlockMinecart represents the Serverbound UpdateCommandBlockMinecart packet.

type UpdateCommandBlockMinecart struct {
	EntityId    int32  `mc:"VarInt"`
	Command     string `mc:"String"`
	TrackOutput bool
}

// PacketID returns the packet ID for this packet.
func (*UpdateCommandBlockMinecart) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundUpdateCommandBlockMinecart
}

// ReadFrom reads the packet data from the reader.
func (p *UpdateCommandBlockMinecart) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var entityId pk.VarInt
	temp, err = entityId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.EntityId = int32(entityId)

	var command pk.String
	temp, err = command.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Command = string(command)

	var trackOutput pk.Boolean
	temp, err = trackOutput.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.TrackOutput = bool(trackOutput)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p UpdateCommandBlockMinecart) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.EntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.String(p.Command).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Boolean(p.TrackOutput).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundUpdateCommandBlockMinecart, func() ServerboundPacket {
		return &UpdateCommandBlockMinecart{}
	})
}
