// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)


// TeleportConfirm represents the Serverbound TeleportConfirm packet.

type TeleportConfirm struct {
	TeleportId int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*TeleportConfirm) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundTeleportConfirm
}


// ReadFrom reads the packet data from the reader.
func (p *TeleportConfirm) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var teleportId pk.VarInt
	temp, err = teleportId.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	p.TeleportId = int32(teleportId)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p TeleportConfirm) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.TeleportId).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}


func init() {
	registerPacket(packetid.ServerboundTeleportConfirm, func() ServerboundPacket {
		return &TeleportConfirm{}
	})
}

