// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// SelectBundleItem represents the Serverbound SelectBundleItem packet.

type SelectBundleItem struct {
	SlotId            int32 `mc:"VarInt"`
	SelectedItemIndex int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*SelectBundleItem) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundSelectBundleItem
}

// ReadFrom reads the packet data from the reader.
func (p *SelectBundleItem) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var slotId pk.VarInt
	temp, err = slotId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.SlotId = int32(slotId)

	var selectedItemIndex pk.VarInt
	temp, err = selectedItemIndex.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.SelectedItemIndex = int32(selectedItemIndex)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p SelectBundleItem) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.SlotId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.SelectedItemIndex).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundSelectBundleItem, func() ServerboundPacket {
		return &SelectBundleItem{}
	})
}
