// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction server

package server

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// Position represents the Serverbound Position packet.

type Position struct {
	X float64
	Y float64
	Z float64
	// Bitflags
	Flags uint8
}

// PacketID returns the packet ID for this packet.
func (*Position) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundPosition
}

// ReadFrom reads the packet data from the reader.
func (p *Position) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.Double)(&p.X).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&p.Y).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&p.Z).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var flags pk.UnsignedByte
	temp, err = flags.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Flags = uint8(flags)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Position) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Double(p.X).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.Y).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.Z).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.UnsignedByte(p.Flags).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ServerboundPosition, func() ServerboundPacket {
		return &Position{}
	})
}
