// Code generated by enhanced-generator; DO NOT EDIT.
package server

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type PlayerInput struct {
	Inputs interface{}
}

func (*PlayerInput) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundPacketID(42)
}

// ReadFrom is a stub (not implemented)
func (p *PlayerInput) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p PlayerInput) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ServerboundPacketID(42), func() ServerboundPacket { return &PlayerInput{} })
}
