// Code generated by github.com/go-mc/packetizer; DO NOT EDIT.

package client

import (
	"errors"
	"io"

	"git.konjactw.dev/falloutBot/go-mc/net/packet"
)

func (c *ConfigClearDialog) ReadFrom(r io.Reader) (n int64, err error) {
	return 0, nil
}

func (c ConfigClearDialog) WriteTo(w io.Writer) (n int64, err error) {
	return 0, nil
}
func (c *ConfigCookieRequest) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Key).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigCookieRequest) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Key).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigCustomPayload) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Channel).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.ByteArray)(&c.Data).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigCustomPayload) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Channel).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.ByteArray)(&c.Data).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigDisconnect) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (&c.Reason).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigDisconnect) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (&c.Reason).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigFinishConfiguration) ReadFrom(r io.Reader) (n int64, err error) {
	return 0, nil
}

func (c ConfigFinishConfiguration) WriteTo(w io.Writer) (n int64, err error) {
	return 0, nil
}
func (c *ConfigKeepAlive) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Long)(&c.ID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigKeepAlive) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Long)(&c.ID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigPing) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Int)(&c.ID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigPing) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Int)(&c.ID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *RegistryData) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Entry).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Boolean)(&c.HasData).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if c.HasData {
		temp, err = packet.NBT(&c.Data).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}
	return n, err
}

func (c RegistryData) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Entry).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Boolean)(&c.HasData).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	if c.HasData {
		temp, err = packet.NBT(&c.Data).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}
	return n, err
}
func (c *ConfigRegistryData) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.RegistryID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = packet.Array(&c.Data).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigRegistryData) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.RegistryID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = packet.Array(&c.Data).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigResetChat) ReadFrom(r io.Reader) (n int64, err error) {
	return 0, nil
}

func (c ConfigResetChat) WriteTo(w io.Writer) (n int64, err error) {
	return 0, nil
}
func (c *KnownPack) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.String)(&c.Namespace).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.String)(&c.ID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.String)(&c.Version).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c KnownPack) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.String)(&c.Namespace).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.String)(&c.ID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.String)(&c.Version).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigSelectKnownPacks) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = packet.Array(&c.KnownPacks).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigSelectKnownPacks) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = packet.Array(&c.KnownPacks).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigStoreCookie) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Key).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*Int8VarIntArray)(&c.Payload).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigStoreCookie) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Key).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*Int8VarIntArray)(&c.Payload).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigTransfer) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.String)(&c.Host).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.VarInt)(&c.Port).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigTransfer) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.String)(&c.Host).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.VarInt)(&c.Port).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigUpdateEnabledFeatures) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*StringIdentifierVarIntArray)(&c.Features).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigUpdateEnabledFeatures) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*StringIdentifierVarIntArray)(&c.Features).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

// Int8VarIntArray a utility type for encoding/decoding packet.Byte -> int8[packet.VarInt] slice.
type Int8VarIntArray []int8

func (a Int8VarIntArray) WriteTo(w io.Writer) (n int64, err error) {
	size := len(a)
	nn, err := packet.VarInt(size).WriteTo(w)
	if err != nil {
		return n, err
	}
	n += nn
	for i := 0; i < size; i++ {
		nn, err := packet.Byte(a[i]).WriteTo(w)
		n += nn
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (a *Int8VarIntArray) ReadFrom(r io.Reader) (n int64, err error) {
	var size packet.VarInt
	nn, err := size.ReadFrom(r)
	n += nn
	if err != nil {
		return n, err
	}
	if size < 0 {
		return n, errors.New("array length less than zero")
	}

	if size > 32767 {
		return n, errors.New("array length greater than 32767")
	}

	if cap(*a) >= int(size) {
		*a = (*a)[:int(size)]
	} else {
		*a = make(Int8VarIntArray, int(size))
	}

	for i := 0; i < int(size); i++ {
		nn, err = (*packet.Byte)(&(*a)[i]).ReadFrom(r)
		n += nn
		if err != nil {
			return n, err
		}
	}

	return n, err
}

// StringIdentifierVarIntArray a utility type for encoding/decoding packet.Identifier -> string[packet.VarInt] slice.
type StringIdentifierVarIntArray []string

func (a StringIdentifierVarIntArray) WriteTo(w io.Writer) (n int64, err error) {
	size := len(a)
	nn, err := packet.VarInt(size).WriteTo(w)
	if err != nil {
		return n, err
	}
	n += nn
	for i := 0; i < size; i++ {
		nn, err := packet.Identifier(a[i]).WriteTo(w)
		n += nn
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (a *StringIdentifierVarIntArray) ReadFrom(r io.Reader) (n int64, err error) {
	var size packet.VarInt
	nn, err := size.ReadFrom(r)
	n += nn
	if err != nil {
		return n, err
	}
	if size < 0 {
		return n, errors.New("array length less than zero")
	}

	if size > 32767 {
		return n, errors.New("array length greater than 32767")
	}

	if cap(*a) >= int(size) {
		*a = (*a)[:int(size)]
	} else {
		*a = make(StringIdentifierVarIntArray, int(size))
	}

	for i := 0; i < int(size); i++ {
		nn, err = (*packet.Identifier)(&(*a)[i]).ReadFrom(r)
		n += nn
		if err != nil {
			return n, err
		}
	}

	return n, err
}
