// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// PlayerRemove represents the Clientbound PlayerRemove packet.

type PlayerRemove struct {
	Players []pk.UUID
}

// PacketID returns the packet ID for this packet.
func (*PlayerRemove) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPlayerRemove
}

// ReadFrom reads the packet data from the reader.
func (p *PlayerRemove) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var playersCount pk.VarInt
	temp, err = playersCount.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Players = make([]pk.UUID, playersCount)
	for i := 0; i < int(playersCount); i++ {
		temp, err = (*pk.UUID)(&s.Players[i]).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p PlayerRemove) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.VarInt(len(p.Players)).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	for i := range p.Players {
		temp, err = s.Players[i].WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundPlayerRemove, func() ClientboundPacket {
		return &PlayerRemove{}
	})
}
