// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// SetTitleTime represents the Clientbound SetTitleTime packet.

type SetTitleTime struct {
	FadeIn  int32
	Stay    int32
	FadeOut int32
}

// PacketID returns the packet ID for this packet.
func (*SetTitleTime) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundSetTitleTime
}

// ReadFrom reads the packet data from the reader.
func (p *SetTitleTime) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	temp, err = (*pk.Int)(&s.FadeIn).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Int)(&s.Stay).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Int)(&s.FadeOut).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p SetTitleTime) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.Int(p.FadeIn).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Int(p.Stay).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Int(p.FadeOut).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundSetTitleTime, func() ClientboundPacket {
		return &SetTitleTime{}
	})
}
