// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// ChunkBatchFinished represents the Clientbound ChunkBatchFinished packet.

type ChunkBatchFinished struct {
	BatchSize int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*ChunkBatchFinished) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundChunkBatchFinished
}

// ReadFrom reads the packet data from the reader.
func (p *ChunkBatchFinished) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var batchSize pk.VarInt
	temp, err = batchSize.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.BatchSize = int32(batchSize)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p ChunkBatchFinished) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.VarInt(p.BatchSize).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundChunkBatchFinished, func() ClientboundPacket {
		return &ChunkBatchFinished{}
	})
}
