// Code generated by enhanced-generator; DO NOT EDIT.
package client

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type TradeList struct {
	WindowId          interface{}
	Trades            []interface{}
	VillagerLevel     int32 `mc:"VarInt"`
	Experience        int32 `mc:"VarInt"`
	IsRegularVillager bool  `mc:"Boolean"`
	CanRestock        bool  `mc:"Boolean"`
}

func (*TradeList) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPacketID(0)
}

// ReadFrom is a stub (not implemented)
func (p *TradeList) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p TradeList) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ClientboundPacketID(0), func() ClientboundPacket { return &TradeList{} })
}
