// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// ChatSuggestions represents the Clientbound ChatSuggestions packet.

type ChatSuggestions struct {
	Action  int32 `mc:"VarInt"`
	Entries []string
}

// PacketID returns the packet ID for this packet.
func (*ChatSuggestions) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundChatSuggestions
}

// ReadFrom reads the packet data from the reader.
func (p *ChatSuggestions) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var action pk.VarInt
	temp, err = action.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Action = int32(action)

	var entriesCount pk.VarInt
	temp, err = entriesCount.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Entries = make([]string, entriesCount)
	for i := 0; i < int(entriesCount); i++ {
		var elem pk.String
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.Entries[i] = string(elem)
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p ChatSuggestions) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.VarInt(p.Action).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(len(p.Entries)).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	for i := range p.Entries {
		temp, err = pk.String(p.Entries[i]).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundChatSuggestions, func() ClientboundPacket {
		return &ChatSuggestions{}
	})
}
