// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/slot"
	"io"
)

// SetCursorItem represents the Clientbound SetCursorItem packet.

type SetCursorItem struct {
	Contents slot.Slot
}

// PacketID returns the packet ID for this packet.
func (*SetCursorItem) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundSetCursorItem
}

// ReadFrom reads the packet data from the reader.
func (p *SetCursorItem) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*slot.Slot)(&p.Contents).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p SetCursorItem) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = p.Contents.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundSetCursorItem, func() ClientboundPacket {
		return &SetCursorItem{}
	})
}
