// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// ChunkBiomesBiomesEntryPosition is a sub-structure used in the packet.
type ChunkBiomesBiomesEntryPosition struct {
	Z int32
	X int32
}


// ReadFrom reads the data from the reader.
func (p *ChunkBiomesBiomesEntryPosition) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.Int)(&p.Z).ReadFrom(r)
	n += temp
	if err != nil { return n, err }

	temp, err = (*pk.Int)(&p.X).ReadFrom(r)
	n += temp
	if err != nil { return n, err }

	return n, nil
}



// WriteTo writes the data to the writer.
func (p ChunkBiomesBiomesEntryPosition) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Int(p.Z).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	temp, err = pk.Int(p.X).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}



// ChunkBiomesBiomesEntry is a sub-structure used in the packet.
type ChunkBiomesBiomesEntry struct {
	Position ChunkBiomesBiomesEntryPosition
	Data []byte `mc:"ByteArray"`
}


// ReadFrom reads the data from the reader.
func (p *ChunkBiomesBiomesEntry) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = p.Position.ReadFrom(r)
	n += temp
	if err != nil { return n, err }

	temp, err = (*pk.ByteArray)(&p.Data).ReadFrom(r)
	n += temp
	if err != nil { return n, err }

	return n, nil
}



// WriteTo writes the data to the writer.
func (p ChunkBiomesBiomesEntry) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = p.Position.WriteTo(w)
	n += temp
	if err != nil { return n, err }

	temp, err = (*pk.ByteArray)(&p.Data).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}




// ChunkBiomes represents the Clientbound ChunkBiomes packet.

type ChunkBiomes struct {
	Biomes []ChunkBiomesBiomesEntry
}

// PacketID returns the packet ID for this packet.
func (*ChunkBiomes) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundChunkBiomes
}


// ReadFrom reads the packet data from the reader.
func (p *ChunkBiomes) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var biomesCount pk.VarInt
	temp, err = biomesCount.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	p.Biomes = make([]ChunkBiomesBiomesEntry, biomesCount)
	for i := 0; i < int(biomesCount); i++ {
		temp, err = p.Biomes[i].ReadFrom(r)
		n += temp
		if err != nil { return n, err }
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p ChunkBiomes) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(len(p.Biomes)).WriteTo(w)
	n += temp
	if err != nil { return n, err }
	for i := range p.Biomes {
		temp, err = p.Biomes[i].WriteTo(w)
		n += temp
		if err != nil { return n, err }
	}

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundChunkBiomes, func() ClientboundPacket {
		return &ChunkBiomes{}
	})
}

