// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// UpdateTime represents the Clientbound UpdateTime packet.

type UpdateTime struct {
	Age         int64
	Time        int64
	TickDayTime bool
}

// PacketID returns the packet ID for this packet.
func (*UpdateTime) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundUpdateTime
}

// ReadFrom reads the packet data from the reader.
func (p *UpdateTime) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	temp, err = (*pk.Long)(&s.Age).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Long)(&s.Time).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var tickDayTime pk.Boolean
	temp, err = tickDayTime.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.TickDayTime = bool(tickDayTime)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p UpdateTime) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.Long(p.Age).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Long(p.Time).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Boolean(p.TickDayTime).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundUpdateTime, func() ClientboundPacket {
		return &UpdateTime{}
	})
}
