// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// EntityEquipment represents the Clientbound EntityEquipment packet.

type EntityEquipment struct {
	EntityId int32 `mc:"VarInt"`
	// TODO: Implement topBitSetTerminatedArray type
	Equipments interface{}
}

// PacketID returns the packet ID for this packet.
func (*EntityEquipment) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundEntityEquipment
}

// ReadFrom reads the packet data from the reader.
func (p *EntityEquipment) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var entityId pk.VarInt
	temp, err = entityId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.EntityId = int32(entityId)

	// TODO: Read Equipments

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p EntityEquipment) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.EntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Equipments

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundEntityEquipment, func() ClientboundPacket {
		return &EntityEquipment{}
	})
}
