// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// AttachEntity represents the Clientbound AttachEntity packet.

type AttachEntity struct {
	EntityId  int32
	VehicleId int32
}

// PacketID returns the packet ID for this packet.
func (*AttachEntity) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundAttachEntity
}

// ReadFrom reads the packet data from the reader.
func (p *AttachEntity) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	temp, err = (*pk.Int)(&s.EntityId).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Int)(&s.VehicleId).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p AttachEntity) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.Int(p.EntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Int(p.VehicleId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundAttachEntity, func() ClientboundPacket {
		return &AttachEntity{}
	})
}
