// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// ScoreboardObjective represents the Clientbound ScoreboardObjective packet.

type ScoreboardObjective struct {
	Name   string `mc:"String"`
	Action int8
	// TODO: Switch type - conditional field based on other field value
	DisplayText interface{}
	// TODO: Switch type - conditional field based on other field value
	Type interface{}
	// TODO: Switch type - conditional field based on other field value
	NumberFormat interface{}
	// TODO: Switch type - conditional field based on other field value
	Styling interface{}
}

// PacketID returns the packet ID for this packet.
func (*ScoreboardObjective) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundScoreboardObjective
}

// ReadFrom reads the packet data from the reader.
func (p *ScoreboardObjective) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var name pk.String
	temp, err = name.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Name = string(name)

	var action int8
	temp, err = (*pk.Byte)(&action).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Action = action

	// TODO: Implement switch field read

	// TODO: Implement switch field read

	// TODO: Implement switch field read

	// TODO: Implement switch field read

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p ScoreboardObjective) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.String(p.Name).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.Action).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Implement switch field write

	// TODO: Implement switch field write

	// TODO: Implement switch field write

	// TODO: Implement switch field write

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundScoreboardObjective, func() ClientboundPacket {
		return &ScoreboardObjective{}
	})
}
