// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)


// WorldBorderWarningReach represents the Clientbound WorldBorderWarningReach packet.

type WorldBorderWarningReach struct {
	WarningBlocks int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*WorldBorderWarningReach) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundWorldBorderWarningReach
}


// ReadFrom reads the packet data from the reader.
func (p *WorldBorderWarningReach) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var warningBlocks pk.VarInt
	temp, err = warningBlocks.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	p.WarningBlocks = int32(warningBlocks)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p WorldBorderWarningReach) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.WarningBlocks).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundWorldBorderWarningReach, func() ClientboundPacket {
		return &WorldBorderWarningReach{}
	})
}

