// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"fmt"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// StopSound represents the Clientbound StopSound packet.

type StopSound struct {
	Flags int8
	// Switch 基於 Flags：
	//   1 -> varint
	//   3 -> varint
	//   default -> void
	Source interface{}
	// Switch 基於 Flags：
	//   2 -> string
	//   3 -> string
	//   default -> void
	Sound interface{}
}

// PacketID returns the packet ID for this packet.
func (*StopSound) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundStopSound
}

// ReadFrom reads the packet data from the reader.
func (p *StopSound) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var flags int8
	temp, err = (*pk.Byte)(&flags).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Flags = flags

	switch p.Flags {
	case 1:
		var val int32
		var elem pk.VarInt
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = int32(elem)
		p.Source = val
	case 3:
		var val int32
		var elem pk.VarInt
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = int32(elem)
		p.Source = val
	default:
		// 無對應負載
	}

	switch p.Flags {
	case 2:
		var val string
		var elem pk.String
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = string(elem)
		p.Sound = val
	case 3:
		var val string
		var elem pk.String
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = string(elem)
		p.Sound = val
	default:
		// 無對應負載
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p StopSound) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Byte(p.Flags).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	switch v := p.Source.(type) {
	case int32:
		temp, err = pk.VarInt(v).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unsupported switch type for Source: %T", v)
	}

	switch v := p.Sound.(type) {
	case string:
		temp, err = pk.String(v).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unsupported switch type for Sound: %T", v)
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundStopSound, func() ClientboundPacket {
		return &StopSound{}
	})
}
