// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// HeldItemSlot represents the Clientbound HeldItemSlot packet.

type HeldItemSlot struct {
	Slot int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*HeldItemSlot) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundHeldItemSlot
}

// ReadFrom reads the packet data from the reader.
func (p *HeldItemSlot) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var slot pk.VarInt
	temp, err = slot.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Slot = int32(slot)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p HeldItemSlot) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.VarInt(p.Slot).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundHeldItemSlot, func() ClientboundPacket {
		return &HeldItemSlot{}
	})
}
