// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)


// EndCombatEvent represents the Clientbound EndCombatEvent packet.

type EndCombatEvent struct {
	Duration int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*EndCombatEvent) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundEndCombatEvent
}


// ReadFrom reads the packet data from the reader.
func (p *EndCombatEvent) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var duration pk.VarInt
	temp, err = duration.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	p.Duration = int32(duration)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p EndCombatEvent) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.Duration).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundEndCombatEvent, func() ClientboundPacket {
		return &EndCombatEvent{}
	})
}

