// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// CloseWindow represents the Clientbound CloseWindow packet.

type CloseWindow struct {
	WindowId int8
}

// PacketID returns the packet ID for this packet.
func (*CloseWindow) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundCloseWindow
}

// ReadFrom reads the packet data from the reader.
func (p *CloseWindow) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	// TODO: Read WindowId (ContainerID)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p CloseWindow) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	// TODO: Write WindowId (ContainerID)

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundCloseWindow, func() ClientboundPacket {
		return &CloseWindow{}
	})
}
