// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// PlayerChatPreviousMessagesEntry is a sub-structure used in the packet.
type PlayerChatPreviousMessagesEntry struct {
	Id int32 `mc:"VarInt"`
	// Optional，當 Id 符合條件時出現
	Signature *[]byte
}

// ReadFrom reads the data from the reader.
func (p *PlayerChatPreviousMessagesEntry) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var id pk.VarInt
	temp, err = id.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Id = int32(id)

	// 當 Id == 0 時讀取 Signature
	if p.Id == 0 {
		var val []byte
		temp, err = (*pk.ByteArray)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.Signature = &val
	}

	return n, nil
}

// WriteTo writes the data to the writer.
func (p PlayerChatPreviousMessagesEntry) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.Id).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	if p.Signature != nil {
		temp, err = pk.ByteArray(*p.Signature).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

// PlayerChat represents the Clientbound PlayerChat packet.

type PlayerChat struct {
	GlobalIndex         int32 `mc:"VarInt"`
	SenderUuid          pk.UUID
	Index               int32 `mc:"VarInt"`
	Signature           *[]byte
	PlainMessage        string `mc:"String"`
	Timestamp           int64
	Salt                int64
	PreviousMessages    []PlayerChatPreviousMessagesEntry
	UnsignedChatContent *pk.NBTField
	FilterType          int32 `mc:"VarInt"`
	// Optional，當 FilterType 符合條件時出現
	FilterTypeMask    *[]int64
	Type              string      `mc:"String"`
	NetworkName       pk.NBTField `mc:"NBT"`
	NetworkTargetName *pk.NBTField
}

// PacketID returns the packet ID for this packet.
func (*PlayerChat) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPlayerChat
}

// ReadFrom reads the packet data from the reader.
func (p *PlayerChat) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var globalIndex pk.VarInt
	temp, err = globalIndex.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.GlobalIndex = int32(globalIndex)

	temp, err = (*pk.UUID)(&p.SenderUuid).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var index pk.VarInt
	temp, err = index.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Index = int32(index)

	var hasSignature pk.Boolean
	temp, err = hasSignature.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if hasSignature {
		var val []byte
		temp, err = (*pk.ByteArray)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.Signature = &val
	}

	var plainMessage pk.String
	temp, err = plainMessage.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.PlainMessage = string(plainMessage)

	temp, err = (*pk.Long)(&p.Timestamp).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Long)(&p.Salt).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var previousMessagesCount pk.VarInt
	temp, err = previousMessagesCount.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.PreviousMessages = make([]PlayerChatPreviousMessagesEntry, previousMessagesCount)
	for i := 0; i < int(previousMessagesCount); i++ {
		temp, err = p.PreviousMessages[i].ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}

	var hasUnsignedChatContent pk.Boolean
	temp, err = hasUnsignedChatContent.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if hasUnsignedChatContent {
		var val pk.NBTField
		temp, err = (*pk.NBTField)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.UnsignedChatContent = &val
	}

	var filterType pk.VarInt
	temp, err = filterType.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.FilterType = int32(filterType)

	// 當 FilterType == 2 時讀取 FilterTypeMask (array)
	if p.FilterType == 2 {
		var cnt pk.VarInt
		temp, err = cnt.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		arr := make([]int64, cnt)
		for i := 0; i < int(cnt); i++ {
			var v int64
			temp, err = (*pk.Long)(&v).ReadFrom(r)
			n += temp
			if err != nil {
				return n, err
			}
			arr[i] = v
		}
		p.FilterTypeMask = &arr
	}

	var _type pk.String
	temp, err = _type.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Type = string(_type)

	temp, err = (*pk.NBTField)(&p.NetworkName).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var hasNetworkTargetName pk.Boolean
	temp, err = hasNetworkTargetName.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if hasNetworkTargetName {
		var val pk.NBTField
		temp, err = (*pk.NBTField)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.NetworkTargetName = &val
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p PlayerChat) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.GlobalIndex).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = p.SenderUuid.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.Index).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	if p.Signature != nil {
		temp, err = pk.Boolean(true).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		temp, err = pk.ByteArray(*p.Signature).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	} else {
		temp, err = pk.Boolean(false).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	temp, err = pk.String(p.PlainMessage).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Long(p.Timestamp).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Long(p.Salt).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(len(p.PreviousMessages)).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	for i := range p.PreviousMessages {
		temp, err = p.PreviousMessages[i].WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	if p.UnsignedChatContent != nil {
		temp, err = pk.Boolean(true).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		temp, err = pk.NBTField(*p.UnsignedChatContent).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	} else {
		temp, err = pk.Boolean(false).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	temp, err = pk.VarInt(p.FilterType).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	if p.FilterTypeMask != nil {
		temp, err = pk.VarInt(len(*p.FilterTypeMask)).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		for i := range *p.FilterTypeMask {
			temp, err = pk.Long((*p.FilterTypeMask)[i]).WriteTo(w)
			n += temp
			if err != nil {
				return n, err
			}
		}
	}

	temp, err = pk.String(p.Type).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = p.NetworkName.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	if p.NetworkTargetName != nil {
		temp, err = pk.Boolean(true).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		temp, err = pk.NBTField(*p.NetworkTargetName).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	} else {
		temp, err = pk.Boolean(false).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundPlayerChat, func() ClientboundPacket {
		return &PlayerChat{}
	})
}
