// Code generated by enhanced-generator; DO NOT EDIT.
package client

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type MapChunk struct {
	X                   int32 `mc:"Int"`
	Z                   int32 `mc:"Int"`
	Heightmaps          []interface{}
	ChunkData           interface{}
	BlockEntities       []interface{}
	SkyLightMask        []interface{}
	BlockLightMask      []interface{}
	EmptySkyLightMask   []interface{}
	EmptyBlockLightMask []interface{}
	SkyLight            []interface{}
	BlockLight          []interface{}
}

func (*MapChunk) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPacketID(0)
}

// ReadFrom is a stub (not implemented)
func (p *MapChunk) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p MapChunk) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ClientboundPacketID(0), func() ClientboundPacket { return &MapChunk{} })
}
