// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"fmt"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// MapIconsEntry is a sub-structure used in the packet.
type MapIconsEntry struct {
	Type        int32 `mc:"VarInt"`
	X           int8
	Z           int8
	Direction   uint8
	DisplayName *pk.NBTField
}

// ReadFrom reads the data from the reader.
func (p *MapIconsEntry) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var _type pk.VarInt
	temp, err = _type.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Type = int32(_type)

	var x int8
	temp, err = (*pk.Byte)(&x).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.X = x

	var z int8
	temp, err = (*pk.Byte)(&z).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Z = z

	var direction pk.UnsignedByte
	temp, err = direction.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Direction = uint8(direction)

	var hasDisplayName pk.Boolean
	temp, err = hasDisplayName.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if hasDisplayName {
		var val pk.NBTField
		temp, err = (*pk.NBTField)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.DisplayName = &val
	}

	return n, nil
}

// WriteTo writes the data to the writer.
func (p MapIconsEntry) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.Type).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.X).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.Z).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.UnsignedByte(p.Direction).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	if p.DisplayName != nil {
		temp, err = pk.Boolean(true).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		temp, err = pk.NBTField(*p.DisplayName).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	} else {
		temp, err = pk.Boolean(false).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

// Map represents the Clientbound Map packet.

type Map struct {
	ItemDamage int32 `mc:"VarInt"`
	Scale      int8
	Locked     bool
	Icons      *[]MapIconsEntry
	Columns    uint8
	// Switch 基於 Columns：
	//   0 -> void
	//   default -> u8
	Rows interface{}
	// Switch 基於 Columns：
	//   0 -> void
	//   default -> u8
	X interface{}
	// Switch 基於 Columns：
	//   0 -> void
	//   default -> u8
	Y interface{}
	// Switch 基於 Columns：
	//   0 -> void

	Data interface{}
}

// PacketID returns the packet ID for this packet.
func (*Map) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundMap
}

// ReadFrom reads the packet data from the reader.
func (p *Map) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var itemDamage pk.VarInt
	temp, err = itemDamage.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.ItemDamage = int32(itemDamage)

	var scale int8
	temp, err = (*pk.Byte)(&scale).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Scale = scale

	var locked pk.Boolean
	temp, err = locked.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Locked = bool(locked)

	var hasIcons pk.Boolean
	temp, err = hasIcons.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if hasIcons {
		var cnt pk.VarInt
		temp, err = cnt.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		arr := make([]MapIconsEntry, cnt)
		for i := 0; i < int(cnt); i++ {
			var v MapIconsEntry
			temp, err = v.ReadFrom(r)
			n += temp
			if err != nil {
				return n, err
			}
			arr[i] = v
		}
		p.Icons = &arr
	}

	var columns pk.UnsignedByte
	temp, err = columns.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Columns = uint8(columns)

	switch p.Columns {
	case 0:
		var val struct{}
		p.Rows = val
	default:
		var val uint8
		var elem pk.UnsignedByte
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = uint8(elem)
		p.Rows = val
	}

	switch p.Columns {
	case 0:
		var val struct{}
		p.X = val
	default:
		var val uint8
		var elem pk.UnsignedByte
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = uint8(elem)
		p.X = val
	}

	switch p.Columns {
	case 0:
		var val struct{}
		p.Y = val
	default:
		var val uint8
		var elem pk.UnsignedByte
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = uint8(elem)
		p.Y = val
	}

	switch p.Columns {
	case 0:
		var val struct{}
		p.Data = val
	default:
		// 無對應負載
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Map) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.ItemDamage).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.Scale).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Boolean(p.Locked).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	if p.Icons != nil {
		temp, err = pk.Boolean(true).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		temp, err = pk.VarInt(len(*p.Icons)).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		for i := range *p.Icons {
			_ = i
			temp, err = (*p.Icons)[i].WriteTo(w)
			n += temp
			if err != nil {
				return n, err
			}
		}
	} else {
		temp, err = pk.Boolean(false).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	temp, err = pk.UnsignedByte(p.Columns).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	switch v := p.Rows.(type) {
	case struct{}:
		if err != nil {
			return n, err
		}
	case uint8:
		temp, err = pk.UnsignedByte(v).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unsupported switch type for Rows: %T", v)
	}

	switch v := p.X.(type) {
	case struct{}:
		if err != nil {
			return n, err
		}
	case uint8:
		temp, err = pk.UnsignedByte(v).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unsupported switch type for X: %T", v)
	}

	switch v := p.Y.(type) {
	case struct{}:
		if err != nil {
			return n, err
		}
	case uint8:
		temp, err = pk.UnsignedByte(v).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unsupported switch type for Y: %T", v)
	}

	switch v := p.Data.(type) {
	case struct{}:
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unsupported switch type for Data: %T", v)
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundMap, func() ClientboundPacket {
		return &Map{}
	})
}
