// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// UpdateViewPosition represents the Clientbound UpdateViewPosition packet.

type UpdateViewPosition struct {
	ChunkX int32 `mc:"VarInt"`
	ChunkZ int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*UpdateViewPosition) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundUpdateViewPosition
}

// ReadFrom reads the packet data from the reader.
func (p *UpdateViewPosition) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var chunkX pk.VarInt
	temp, err = chunkX.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.ChunkX = int32(chunkX)

	var chunkZ pk.VarInt
	temp, err = chunkZ.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.ChunkZ = int32(chunkZ)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p UpdateViewPosition) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.VarInt(p.ChunkX).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.ChunkZ).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundUpdateViewPosition, func() ClientboundPacket {
		return &UpdateViewPosition{}
	})
}
