// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// SpawnPosition represents the Clientbound SpawnPosition packet.

type SpawnPosition struct {
	Location pk.Position
	Angle    float32
}

// PacketID returns the packet ID for this packet.
func (*SpawnPosition) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundSpawnPosition
}

// ReadFrom reads the packet data from the reader.
func (p *SpawnPosition) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	temp, err = (*pk.Position)(&s.Location).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&s.Angle).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p SpawnPosition) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = s.Location.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.Angle).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundSpawnPosition, func() ClientboundPacket {
		return &SpawnPosition{}
	})
}
