// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// FacePlayer represents the Clientbound FacePlayer packet.

type FacePlayer struct {
	FeetEyes int32 `mc:"VarInt"`
	X        float64
	Y        float64
	Z        float64
	IsEntity bool
	// TODO: Switch type - conditional field based on other field value
	EntityId interface{}
	// TODO: Switch type - conditional field based on other field value
	EntityFeetEyes interface{}
}

// PacketID returns the packet ID for this packet.
func (*FacePlayer) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundFacePlayer
}

// ReadFrom reads the packet data from the reader.
func (p *FacePlayer) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var feetEyes pk.VarInt
	temp, err = feetEyes.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.FeetEyes = int32(feetEyes)

	temp, err = (*pk.Double)(&s.X).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&s.Y).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&s.Z).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var isEntity pk.Boolean
	temp, err = isEntity.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.IsEntity = bool(isEntity)

	// TODO: Implement switch field read

	// TODO: Implement switch field read

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p FacePlayer) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.VarInt(p.FeetEyes).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.X).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.Y).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.Z).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Boolean(p.IsEntity).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Implement switch field write

	// TODO: Implement switch field write

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundFacePlayer, func() ClientboundPacket {
		return &FacePlayer{}
	})
}
