// Code generated by enhanced-generator; DO NOT EDIT.
package client

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type Position struct {
	TeleportId int32   `mc:"VarInt"`
	X          float64 `mc:"Double"`
	Y          float64 `mc:"Double"`
	Z          float64 `mc:"Double"`
	Dx         float64 `mc:"Double"`
	Dy         float64 `mc:"Double"`
	Dz         float64 `mc:"Double"`
	Yaw        float32 `mc:"Float"`
	Pitch      float32 `mc:"Float"`
	Flags      interface{}
}

func (*Position) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPacketID(0)
}

// ReadFrom is a stub (not implemented)
func (p *Position) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p Position) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ClientboundPacketID(0), func() ClientboundPacket { return &Position{} })
}
