// Code generated by enhanced-generator; DO NOT EDIT.
package client

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type SystemChat struct {
	Content     pk.NBTField
	IsActionBar bool `mc:"Boolean"`
}

func (*SystemChat) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPacketID(114)
}

// ReadFrom is a stub (not implemented)
func (p *SystemChat) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p SystemChat) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ClientboundPacketID(114), func() ClientboundPacket { return &SystemChat{} })
}
