// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// BossBar represents the Clientbound BossBar packet.

type BossBar struct {
	EntityUUID pk.UUID
	Action     int32 `mc:"VarInt"`
	// TODO: Switch type - conditional field based on other field value
	Title interface{}
	// TODO: Switch type - conditional field based on other field value
	Health interface{}
	// TODO: Switch type - conditional field based on other field value
	Color interface{}
	// TODO: Switch type - conditional field based on other field value
	Dividers interface{}
	// TODO: Switch type - conditional field based on other field value
	Flags interface{}
}

// PacketID returns the packet ID for this packet.
func (*BossBar) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundBossBar
}

// ReadFrom reads the packet data from the reader.
func (p *BossBar) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	temp, err = (*pk.UUID)(&s.EntityUUID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var action pk.VarInt
	temp, err = action.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Action = int32(action)

	// TODO: Implement switch field read

	// TODO: Implement switch field read

	// TODO: Implement switch field read

	// TODO: Implement switch field read

	// TODO: Implement switch field read

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p BossBar) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = s.EntityUUID.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.Action).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Implement switch field write

	// TODO: Implement switch field write

	// TODO: Implement switch field write

	// TODO: Implement switch field write

	// TODO: Implement switch field write

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundBossBar, func() ClientboundPacket {
		return &BossBar{}
	})
}
