// Code generated by enhanced-generator v2; DO NOT EDIT.

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	packetid "git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
)

// ClientboundPacket 定義所有遊戲階段封包介面（Clientbound）
type ClientboundPacket interface {
	pk.Field
	PacketID() packetid.ClientboundPacketID
}

type ClientboundPacketCreator func() ClientboundPacket

// ClientboundPackets 供外部透過 ID 生成封包實例
var ClientboundPackets = make(map[packetid.ClientboundPacketID]ClientboundPacketCreator)

func registerPacket(id packetid.ClientboundPacketID, creator ClientboundPacketCreator) {
	ClientboundPackets[id] = creator
}
