// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)


// StartConfiguration represents the Clientbound StartConfiguration packet.

type StartConfiguration struct {
}

// PacketID returns the packet ID for this packet.
func (*StartConfiguration) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundStartConfiguration
}


// ReadFrom reads the packet data from the reader.
func (p *StartConfiguration) ReadFrom(r io.Reader) (n int64, err error) {

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p StartConfiguration) WriteTo(w io.Writer) (n int64, err error) {

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundStartConfiguration, func() ClientboundPacket {
		return &StartConfiguration{}
	})
}

