// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// Position represents the Clientbound Position packet.

type Position struct {
	TeleportId int32 `mc:"VarInt"`
	X          float64
	Y          float64
	Z          float64
	Dx         float64
	Dy         float64
	Dz         float64
	Yaw        float32
	Pitch      float32
	Flags      int32
}

// PacketID returns the packet ID for this packet.
func (*Position) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPosition
}

// ReadFrom reads the packet data from the reader.
func (p *Position) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var teleportId pk.VarInt
	temp, err = teleportId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.TeleportId = int32(teleportId)

	temp, err = (*pk.Double)(&s.X).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&s.Y).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&s.Z).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&s.Dx).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&s.Dy).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&s.Dz).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&s.Yaw).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&s.Pitch).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Read Flags (PositionUpdateRelatives)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Position) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.VarInt(p.TeleportId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.X).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.Y).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.Z).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.Dx).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.Dy).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.Dz).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.Yaw).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.Pitch).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Flags (PositionUpdateRelatives)

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundPosition, func() ClientboundPacket {
		return &Position{}
	})
}
