// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// MoveMinecartStepsEntry is a sub-structure used in the packet.
type MoveMinecartStepsEntry struct {
	Position [3]float32
	Movement [3]float32
	Yaw      float32
	Pitch    float32
	Weight   float32
}

// ReadFrom reads the data from the reader.
func (p *MoveMinecartStepsEntry) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Read Position (vec3f)

	// TODO: Read Movement (vec3f)

	temp, err = (*pk.Float)(&p.Yaw).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&p.Pitch).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&p.Weight).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the data to the writer.
func (p MoveMinecartStepsEntry) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Write Position (vec3f)

	// TODO: Write Movement (vec3f)

	temp, err = pk.Float(p.Yaw).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.Pitch).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.Weight).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// MoveMinecart represents the Clientbound MoveMinecart packet.

type MoveMinecart struct {
	EntityId int32 `mc:"VarInt"`
	Steps    []MoveMinecartStepsEntry
}

// PacketID returns the packet ID for this packet.
func (*MoveMinecart) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundMoveMinecart
}

// ReadFrom reads the packet data from the reader.
func (p *MoveMinecart) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var entityId pk.VarInt
	temp, err = entityId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.EntityId = int32(entityId)

	var stepsCount pk.VarInt
	temp, err = stepsCount.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Steps = make([]MoveMinecartStepsEntry, stepsCount)
	for i := 0; i < int(stepsCount); i++ {
		temp, err = p.Steps[i].ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p MoveMinecart) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.EntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(len(p.Steps)).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	for i := range p.Steps {
		temp, err = p.Steps[i].WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundMoveMinecart, func() ClientboundPacket {
		return &MoveMinecart{}
	})
}
