// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"fmt"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// BossBar represents the Clientbound BossBar packet.

type BossBar struct {
	EntityUUID pk.UUID
	Action     int32 `mc:"VarInt"`
	// Switch 基於 Action：
	//   0 -> anonymousNbt
	//   3 -> anonymousNbt
	//   default -> void
	Title interface{}
	// Switch 基於 Action：
	//   0 -> f32
	//   2 -> f32
	//   default -> void
	Health interface{}
	// Switch 基於 Action：
	//   0 -> varint
	//   4 -> varint
	//   default -> void
	Color interface{}
	// Switch 基於 Action：
	//   0 -> varint
	//   4 -> varint
	//   default -> void
	Dividers interface{}
	// Switch 基於 Action：
	//   0 -> u8
	//   5 -> u8
	//   default -> void
	Flags interface{}
}

// PacketID returns the packet ID for this packet.
func (*BossBar) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundBossBar
}

// ReadFrom reads the packet data from the reader.
func (p *BossBar) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.UUID)(&p.EntityUUID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var action pk.VarInt
	temp, err = action.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Action = int32(action)

	switch p.Action {
	case 0:
		var val pk.NBTField
		temp, err = (*pk.NBTField)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.Title = val
	case 3:
		var val pk.NBTField
		temp, err = (*pk.NBTField)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.Title = val
	default:
		// 無對應負載
	}

	switch p.Action {
	case 0:
		var val float32
		temp, err = (*pk.Float)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.Health = val
	case 2:
		var val float32
		temp, err = (*pk.Float)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.Health = val
	default:
		// 無對應負載
	}

	switch p.Action {
	case 4:
		var val int32
		var elem pk.VarInt
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = int32(elem)
		p.Color = val
	case 0:
		var val int32
		var elem pk.VarInt
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = int32(elem)
		p.Color = val
	default:
		// 無對應負載
	}

	switch p.Action {
	case 0:
		var val int32
		var elem pk.VarInt
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = int32(elem)
		p.Dividers = val
	case 4:
		var val int32
		var elem pk.VarInt
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = int32(elem)
		p.Dividers = val
	default:
		// 無對應負載
	}

	switch p.Action {
	case 0:
		var val uint8
		var elem pk.UnsignedByte
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = uint8(elem)
		p.Flags = val
	case 5:
		var val uint8
		var elem pk.UnsignedByte
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		val = uint8(elem)
		p.Flags = val
	default:
		// 無對應負載
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p BossBar) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = p.EntityUUID.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.Action).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	switch v := p.Title.(type) {
	case pk.NBTField:
		temp, err = pk.NBTField(v).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unsupported switch type for Title: %T", v)
	}

	switch v := p.Health.(type) {
	case float32:
		temp, err = pk.Float(v).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unsupported switch type for Health: %T", v)
	}

	switch v := p.Color.(type) {
	case int32:
		temp, err = pk.VarInt(v).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unsupported switch type for Color: %T", v)
	}

	switch v := p.Dividers.(type) {
	case int32:
		temp, err = pk.VarInt(v).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unsupported switch type for Dividers: %T", v)
	}

	switch v := p.Flags.(type) {
	case uint8:
		temp, err = pk.UnsignedByte(v).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	default:
		return n, fmt.Errorf("unsupported switch type for Flags: %T", v)
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundBossBar, func() ClientboundPacket {
		return &BossBar{}
	})
}
