// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// WorldParticles represents the Clientbound WorldParticles packet.

type WorldParticles struct {
	LongDistance   bool
	AlwaysShow     bool
	X              float64
	Y              float64
	Z              float64
	OffsetX        float32
	OffsetY        float32
	OffsetZ        float32
	VelocityOffset float32
	Amount         int32
	Particle       interface{}
}

// PacketID returns the packet ID for this packet.
func (*WorldParticles) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundWorldParticles
}

// ReadFrom reads the packet data from the reader.
func (p *WorldParticles) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var longDistance pk.Boolean
	temp, err = longDistance.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.LongDistance = bool(longDistance)

	var alwaysShow pk.Boolean
	temp, err = alwaysShow.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.AlwaysShow = bool(alwaysShow)

	temp, err = (*pk.Double)(&p.X).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&p.Y).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&p.Z).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&p.OffsetX).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&p.OffsetY).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&p.OffsetZ).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&p.VelocityOffset).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Int)(&p.Amount).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Read Particle (unsupported type Particle)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p WorldParticles) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Boolean(p.LongDistance).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Boolean(p.AlwaysShow).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.X).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.Y).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.Z).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.OffsetX).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.OffsetY).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.OffsetZ).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.VelocityOffset).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Int(p.Amount).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Particle (unsupported type Particle)

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundWorldParticles, func() ClientboundPacket {
		return &WorldParticles{}
	})
}
