// Code generated by enhanced-generator; DO NOT EDIT.
package client

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type RecipeBookRemove struct {
	RecipeIds []interface{}
}

func (*RecipeBookRemove) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPacketID(68)
}

// ReadFrom is a stub (not implemented)
func (p *RecipeBookRemove) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p RecipeBookRemove) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ClientboundPacketID(68), func() ClientboundPacket { return &RecipeBookRemove{} })
}
