// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// SystemChat represents the Clientbound SystemChat packet.

type SystemChat struct {
	Content     pk.NBT `mc:"NBT"`
	IsActionBar bool
}

// PacketID returns the packet ID for this packet.
func (*SystemChat) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundSystemChat
}

// ReadFrom reads the packet data from the reader.
func (p *SystemChat) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	temp, err = (*pk.NBT)(&s.Content).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var isActionBar pk.Boolean
	temp, err = isActionBar.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.IsActionBar = bool(isActionBar)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p SystemChat) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = s.Content.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Boolean(p.IsActionBar).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundSystemChat, func() ClientboundPacket {
		return &SystemChat{}
	})
}
