// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)


// OpenBook represents the Clientbound OpenBook packet.

type OpenBook struct {
	Hand int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*OpenBook) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundOpenBook
}


// ReadFrom reads the packet data from the reader.
func (p *OpenBook) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var hand pk.VarInt
	temp, err = hand.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	p.Hand = int32(hand)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p OpenBook) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.Hand).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundOpenBook, func() ClientboundPacket {
		return &OpenBook{}
	})
}

