// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// SoundEffect represents the Clientbound SoundEffect packet.

type SoundEffect struct {
	Sound         interface{}
	SoundCategory int32
	X             int32
	Y             int32
	Z             int32
	Volume        float32
	Pitch         float32
	Seed          int64
}

// PacketID returns the packet ID for this packet.
func (*SoundEffect) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundSoundEffect
}

// ReadFrom reads the packet data from the reader.
func (p *SoundEffect) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Read Sound (unsupported type ItemSoundHolder)

	// TODO: Read SoundCategory (soundSource)

	temp, err = (*pk.Int)(&p.X).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Int)(&p.Y).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Int)(&p.Z).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&p.Volume).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&p.Pitch).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Long)(&p.Seed).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p SoundEffect) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Write Sound (unsupported type ItemSoundHolder)

	// TODO: Write SoundCategory (soundSource)

	temp, err = pk.Int(p.X).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Int(p.Y).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Int(p.Z).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.Volume).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.Pitch).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Long(p.Seed).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundSoundEffect, func() ClientboundPacket {
		return &SoundEffect{}
	})
}
