// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// Ping represents the Clientbound Ping packet.

type Ping struct {
	Id int32
}

// PacketID returns the packet ID for this packet.
func (*Ping) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPing
}

// ReadFrom reads the packet data from the reader.
func (p *Ping) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	temp, err = (*pk.Int)(&s.Id).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Ping) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.Int(p.Id).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundPing, func() ClientboundPacket {
		return &Ping{}
	})
}
