// Code generated by enhanced-generator; DO NOT EDIT.
package client

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type InitializeWorldBorder struct {
	X                      float64 `mc:"Double"`
	Z                      float64 `mc:"Double"`
	OldDiameter            float64 `mc:"Double"`
	NewDiameter            float64 `mc:"Double"`
	Speed                  int32   `mc:"VarInt"`
	PortalTeleportBoundary int32   `mc:"VarInt"`
	WarningBlocks          int32   `mc:"VarInt"`
	WarningTime            int32   `mc:"VarInt"`
}

func (*InitializeWorldBorder) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPacketID(0)
}

// ReadFrom is a stub (not implemented)
func (p *InitializeWorldBorder) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p InitializeWorldBorder) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ClientboundPacketID(0), func() ClientboundPacket { return &InitializeWorldBorder{} })
}
