// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// PlayerRotation represents the Clientbound PlayerRotation packet.

type PlayerRotation struct {
	Yaw   float32
	Pitch float32
}

// PacketID returns the packet ID for this packet.
func (*PlayerRotation) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPlayerRotation
}

// ReadFrom reads the packet data from the reader.
func (p *PlayerRotation) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.Float)(&p.Yaw).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&p.Pitch).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p PlayerRotation) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Float(p.Yaw).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.Pitch).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundPlayerRotation, func() ClientboundPacket {
		return &PlayerRotation{}
	})
}
