// Code generated by enhanced-generator; DO NOT EDIT.
package client

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type DamageEvent struct {
	EntityId       int32 `mc:"VarInt"`
	SourceTypeId   int32 `mc:"VarInt"`
	SourceCauseId  int32 `mc:"VarInt"`
	SourceDirectId int32 `mc:"VarInt"`
	SourcePosition interface{}
}

func (*DamageEvent) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPacketID(25)
}

// ReadFrom is a stub (not implemented)
func (p *DamageEvent) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p DamageEvent) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ClientboundPacketID(25), func() ClientboundPacket { return &DamageEvent{} })
}
