// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// PlayerChat represents the Clientbound PlayerChat packet.

type PlayerChat struct {
	GlobalIndex int32 `mc:"VarInt"`
	SenderUuid  pk.UUID
	Index       int32 `mc:"VarInt"`
	Signature
	PlainMessage        string `mc:"String"`
	Timestamp           int64
	Salt                int64
	PreviousMessages    interface{}
	UnsignedChatContent *pk.NBT
	FilterType          int32 `mc:"VarInt"`
	// TODO: Switch type - conditional field based on other field value
	FilterTypeMask    interface{}
	Type              interface{}
	NetworkName       pk.NBT `mc:"NBT"`
	NetworkTargetName *pk.NBT
}

// PacketID returns the packet ID for this packet.
func (*PlayerChat) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPlayerChat
}

// ReadFrom reads the packet data from the reader.
func (p *PlayerChat) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var globalIndex pk.VarInt
	temp, err = globalIndex.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.GlobalIndex = int32(globalIndex)

	temp, err = (*pk.UUID)(&s.SenderUuid).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var index pk.VarInt
	temp, err = index.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Index = int32(index)

	var plainMessage pk.String
	temp, err = plainMessage.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.PlainMessage = string(plainMessage)

	temp, err = (*pk.Long)(&s.Timestamp).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Long)(&s.Salt).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Read PreviousMessages (previousMessages)

	var hasUnsignedChatContent pk.Boolean
	temp, err = hasUnsignedChatContent.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if hasUnsignedChatContent {
		var val pk.NBT
		temp, err = (*pk.NBT)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		s.UnsignedChatContent = &val
	}

	var filterType pk.VarInt
	temp, err = filterType.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.FilterType = int32(filterType)

	// TODO: Implement switch field read

	// TODO: Read Type (ChatTypesHolder)

	temp, err = (*pk.NBT)(&s.NetworkName).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var hasNetworkTargetName pk.Boolean
	temp, err = hasNetworkTargetName.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if hasNetworkTargetName {
		var val pk.NBT
		temp, err = (*pk.NBT)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		s.NetworkTargetName = &val
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p PlayerChat) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.VarInt(p.GlobalIndex).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = s.SenderUuid.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.Index).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.String(p.PlainMessage).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Long(p.Timestamp).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Long(p.Salt).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write PreviousMessages (previousMessages)

	if p.UnsignedChatContent != nil {
		temp, err = pk.Boolean(true).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		temp, err = s.UnsignedChatContent.WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	} else {
		temp, err = pk.Boolean(false).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	temp, err = pk.VarInt(p.FilterType).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Implement switch field write

	// TODO: Write Type (ChatTypesHolder)

	temp, err = s.NetworkName.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	if p.NetworkTargetName != nil {
		temp, err = pk.Boolean(true).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		temp, err = s.NetworkTargetName.WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	} else {
		temp, err = pk.Boolean(false).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundPlayerChat, func() ClientboundPacket {
		return &PlayerChat{}
	})
}
