// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// EntityHeadRotation represents the Clientbound EntityHeadRotation packet.

type EntityHeadRotation struct {
	EntityId int32 `mc:"VarInt"`
	HeadYaw  int8
}

// PacketID returns the packet ID for this packet.
func (*EntityHeadRotation) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundEntityHeadRotation
}

// ReadFrom reads the packet data from the reader.
func (p *EntityHeadRotation) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var entityId pk.VarInt
	temp, err = entityId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.EntityId = int32(entityId)

	var headYaw int8
	temp, err = (*pk.Byte)(&headYaw).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.HeadYaw = headYaw

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p EntityHeadRotation) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.VarInt(p.EntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.HeadYaw).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundEntityHeadRotation, func() ClientboundPacket {
		return &EntityHeadRotation{}
	})
}
