// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)


// StepTick represents the Clientbound StepTick packet.

type StepTick struct {
	TickSteps int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*StepTick) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundStepTick
}


// ReadFrom reads the packet data from the reader.
func (p *StepTick) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var tickSteps pk.VarInt
	temp, err = tickSteps.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	p.TickSteps = int32(tickSteps)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p StepTick) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.TickSteps).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundStepTick, func() ClientboundPacket {
		return &StepTick{}
	})
}

