// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// PingResponse represents the Clientbound PingResponse packet.

type PingResponse struct {
	Id int64
}

// PacketID returns the packet ID for this packet.
func (*PingResponse) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPingResponse
}

// ReadFrom reads the packet data from the reader.
func (p *PingResponse) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	temp, err = (*pk.Long)(&s.Id).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p PingResponse) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.Long(p.Id).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundPingResponse, func() ClientboundPacket {
		return &PingResponse{}
	})
}
