// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/metadata"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)


// EntityMetadata represents the Clientbound EntityMetadata packet.

type EntityMetadata struct {
	EntityId int32 `mc:"VarInt"`
	Metadata metadata.EntityMetadata
}

// PacketID returns the packet ID for this packet.
func (*EntityMetadata) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundEntityMetadata
}


// ReadFrom reads the packet data from the reader.
func (p *EntityMetadata) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var entityId pk.VarInt
	temp, err = entityId.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	p.EntityId = int32(entityId)

	temp, err = (*metadata.EntityMetadata)(&p.Metadata).ReadFrom(r)
	n += temp
	if err != nil { return n, err }

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p EntityMetadata) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.EntityId).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	temp, err = p.Metadata.WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundEntityMetadata, func() ClientboundPacket {
		return &EntityMetadata{}
	})
}

