// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// CraftProgressBar represents the Clientbound CraftProgressBar packet.

type CraftProgressBar struct {
	WindowId int8
	Property int16
	Value    int16
}

// PacketID returns the packet ID for this packet.
func (*CraftProgressBar) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundCraftProgressBar
}

// ReadFrom reads the packet data from the reader.
func (p *CraftProgressBar) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	// TODO: Read WindowId (ContainerID)

	temp, err = (*pk.Short)(&s.Property).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Short)(&s.Value).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p CraftProgressBar) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	// TODO: Write WindowId (ContainerID)

	temp, err = pk.Short(p.Property).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Short(p.Value).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundCraftProgressBar, func() ClientboundPacket {
		return &CraftProgressBar{}
	})
}
