// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// Collect represents the Clientbound Collect packet.

type Collect struct {
	CollectedEntityId int32 `mc:"VarInt"`
	CollectorEntityId int32 `mc:"VarInt"`
	PickupItemCount   int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*Collect) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundCollect
}

// ReadFrom reads the packet data from the reader.
func (p *Collect) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var collectedEntityId pk.VarInt
	temp, err = collectedEntityId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.CollectedEntityId = int32(collectedEntityId)

	var collectorEntityId pk.VarInt
	temp, err = collectorEntityId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.CollectorEntityId = int32(collectorEntityId)

	var pickupItemCount pk.VarInt
	temp, err = pickupItemCount.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.PickupItemCount = int32(pickupItemCount)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Collect) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.CollectedEntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.CollectorEntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.PickupItemCount).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundCollect, func() ClientboundPacket {
		return &Collect{}
	})
}
