// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// EntitySoundEffect represents the Clientbound EntitySoundEffect packet.

type EntitySoundEffect struct {
	Sound         interface{}
	SoundCategory int32
	EntityId      int32 `mc:"VarInt"`
	Volume        float32
	Pitch         float32
	Seed          int64
}

// PacketID returns the packet ID for this packet.
func (*EntitySoundEffect) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundEntitySoundEffect
}

// ReadFrom reads the packet data from the reader.
func (p *EntitySoundEffect) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Read Sound (unsupported type ItemSoundHolder)

	// TODO: Read SoundCategory (soundSource)

	var entityId pk.VarInt
	temp, err = entityId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.EntityId = int32(entityId)

	temp, err = (*pk.Float)(&p.Volume).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Float)(&p.Pitch).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Long)(&p.Seed).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p EntitySoundEffect) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Write Sound (unsupported type ItemSoundHolder)

	// TODO: Write SoundCategory (soundSource)

	temp, err = pk.VarInt(p.EntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.Volume).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Float(p.Pitch).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Long(p.Seed).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundEntitySoundEffect, func() ClientboundPacket {
		return &EntitySoundEffect{}
	})
}
