// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// BlockBreakAnimation represents the Clientbound BlockBreakAnimation packet.

type BlockBreakAnimation struct {
	EntityId     int32 `mc:"VarInt"`
	Location     pk.Position
	DestroyStage int8
}

// PacketID returns the packet ID for this packet.
func (*BlockBreakAnimation) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundBlockBreakAnimation
}

// ReadFrom reads the packet data from the reader.
func (p *BlockBreakAnimation) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var entityId pk.VarInt
	temp, err = entityId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.EntityId = int32(entityId)

	temp, err = (*pk.Position)(&p.Location).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var destroyStage int8
	temp, err = (*pk.Byte)(&destroyStage).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.DestroyStage = destroyStage

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p BlockBreakAnimation) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.EntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = p.Location.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.DestroyStage).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundBlockBreakAnimation, func() ClientboundPacket {
		return &BlockBreakAnimation{}
	})
}
