// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)


// UnloadChunk represents the Clientbound UnloadChunk packet.

type UnloadChunk struct {
	ChunkZ int32
	ChunkX int32
}

// PacketID returns the packet ID for this packet.
func (*UnloadChunk) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundUnloadChunk
}


// ReadFrom reads the packet data from the reader.
func (p *UnloadChunk) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.Int)(&p.ChunkZ).ReadFrom(r)
	n += temp
	if err != nil { return n, err }

	temp, err = (*pk.Int)(&p.ChunkX).ReadFrom(r)
	n += temp
	if err != nil { return n, err }

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p UnloadChunk) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Int(p.ChunkZ).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	temp, err = pk.Int(p.ChunkX).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundUnloadChunk, func() ClientboundPacket {
		return &UnloadChunk{}
	})
}

