// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// GameStateChange represents the Clientbound GameStateChange packet.

type GameStateChange struct {
	// TODO: Implement mapper type
	Reason   interface{}
	GameMode float32
}

// PacketID returns the packet ID for this packet.
func (*GameStateChange) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundGameStateChange
}

// ReadFrom reads the packet data from the reader.
func (p *GameStateChange) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	// TODO: Read Reason

	temp, err = (*pk.Float)(&s.GameMode).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p GameStateChange) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	// TODO: Write Reason

	temp, err = pk.Float(p.GameMode).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundGameStateChange, func() ClientboundPacket {
		return &GameStateChange{}
	})
}
