// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// SetTickingState represents the Clientbound SetTickingState packet.

type SetTickingState struct {
	TickRate float32
	IsFrozen bool
}

// PacketID returns the packet ID for this packet.
func (*SetTickingState) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundSetTickingState
}

// ReadFrom reads the packet data from the reader.
func (p *SetTickingState) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	temp, err = (*pk.Float)(&s.TickRate).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var isFrozen pk.Boolean
	temp, err = isFrozen.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.IsFrozen = bool(isFrozen)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p SetTickingState) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.Float(p.TickRate).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Boolean(p.IsFrozen).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundSetTickingState, func() ClientboundPacket {
		return &SetTickingState{}
	})
}
