// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// CraftRecipeResponse represents the Clientbound CraftRecipeResponse packet.

type CraftRecipeResponse struct {
	WindowId      int8
	RecipeDisplay interface{}
}

// PacketID returns the packet ID for this packet.
func (*CraftRecipeResponse) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundCraftRecipeResponse
}

// ReadFrom reads the packet data from the reader.
func (p *CraftRecipeResponse) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Read WindowId (ContainerID)

	// TODO: Read RecipeDisplay (unsupported type RecipeDisplay)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p CraftRecipeResponse) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Write WindowId (ContainerID)

	// TODO: Write RecipeDisplay (unsupported type RecipeDisplay)

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundCraftRecipeResponse, func() ClientboundPacket {
		return &CraftRecipeResponse{}
	})
}
