// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// SimulationDistance represents the Clientbound SimulationDistance packet.

type SimulationDistance struct {
	Distance int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*SimulationDistance) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundSimulationDistance
}

// ReadFrom reads the packet data from the reader.
func (p *SimulationDistance) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var distance pk.VarInt
	temp, err = distance.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Distance = int32(distance)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p SimulationDistance) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.Distance).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundSimulationDistance, func() ClientboundPacket {
		return &SimulationDistance{}
	})
}
