// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// Map represents the Clientbound Map packet.

type Map struct {
	ItemDamage int32 `mc:"VarInt"`
	Scale      int8
	Locked     bool
	Icons
	Columns uint8
	// TODO: Switch type - conditional field based on other field value
	Rows interface{}
	// TODO: Switch type - conditional field based on other field value
	X interface{}
	// TODO: Switch type - conditional field based on other field value
	Y interface{}
	// TODO: Switch type - conditional field based on other field value
	Data interface{}
}

// PacketID returns the packet ID for this packet.
func (*Map) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundMap
}

// ReadFrom reads the packet data from the reader.
func (p *Map) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var itemDamage pk.VarInt
	temp, err = itemDamage.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.ItemDamage = int32(itemDamage)

	var scale int8
	temp, err = (*pk.Byte)(&scale).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Scale = scale

	var locked pk.Boolean
	temp, err = locked.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Locked = bool(locked)

	// TODO: Read Columns (u8)

	// TODO: Implement switch field read

	// TODO: Implement switch field read

	// TODO: Implement switch field read

	// TODO: Implement switch field read

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Map) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.VarInt(p.ItemDamage).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Byte(p.Scale).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Boolean(p.Locked).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Columns (u8)

	// TODO: Implement switch field write

	// TODO: Implement switch field write

	// TODO: Implement switch field write

	// TODO: Implement switch field write

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundMap, func() ClientboundPacket {
		return &Map{}
	})
}
