// Code generated by enhanced-generator; DO NOT EDIT.
package client

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type ScoreboardScore struct {
	ItemName     string `mc:"String"`
	ScoreName    string `mc:"String"`
	Value        int32  `mc:"VarInt"`
	DisplayName  interface{}
	NumberFormat interface{}
	Styling      interface{}
}

func (*ScoreboardScore) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPacketID(0)
}

// ReadFrom is a stub (not implemented)
func (p *ScoreboardScore) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p ScoreboardScore) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ClientboundPacketID(0), func() ClientboundPacket { return &ScoreboardScore{} })
}
