// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"fmt"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)


// Teams represents the Clientbound Teams packet.

type Teams struct {
	Team string `mc:"String"`
	// Mapper to string
	Mode string
	// Switch 基於 Mode：
//   add -> [array map[countType:varint type:string]]
//   join -> [array map[countType:varint type:string]]
//   leave -> [array map[countType:varint type:string]]
//   default -> void
	Players interface{}
}

// PacketID returns the packet ID for this packet.
func (*Teams) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundTeams
}


// ReadFrom reads the packet data from the reader.
func (p *Teams) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var team pk.String
	temp, err = team.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	p.Team = string(team)

	var mapperVal pk.Byte
	temp, err = mapperVal.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	switch mapperVal {
	case 0:
		p.Mode = "add"
	case 1:
		p.Mode = "remove"
	case 2:
		p.Mode = "change"
	case 3:
		p.Mode = "join"
	case 4:
		p.Mode = "leave"
	default:
		return n, fmt.Errorf("unknown mapper value %d for Mode", mapperVal)
	}

	switch p.Mode {
	default:
		// 無對應負載
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Teams) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.String(p.Team).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	switch p.Mode {
	case "add":
		temp, err = pk.Byte(0).WriteTo(w)
		n += temp
		if err != nil { return n, err }
	case "remove":
		temp, err = pk.Byte(1).WriteTo(w)
		n += temp
		if err != nil { return n, err }
	case "change":
		temp, err = pk.Byte(2).WriteTo(w)
		n += temp
		if err != nil { return n, err }
	case "join":
		temp, err = pk.Byte(3).WriteTo(w)
		n += temp
		if err != nil { return n, err }
	case "leave":
		temp, err = pk.Byte(4).WriteTo(w)
		n += temp
		if err != nil { return n, err }
	default:
		return n, fmt.Errorf("unknown Mode value %v", p.Mode)
	}

	switch v := p.Players.(type) {
	default:
		return n, fmt.Errorf("unsupported switch type for Players: %T", v)
	}

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundTeams, func() ClientboundPacket {
		return &Teams{}
	})
}

