// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// RecipeBookAddEntriesEntryRecipe is a sub-structure used in the packet.
type RecipeBookAddEntriesEntryRecipe struct {
	DisplayId int32 `mc:"VarInt"`
	Display   interface{}
	Group     *int32 `mc:"VarInt"`
	// TODO: Implement mapper type
	Category interface{}
	// TODO: Optional complex type
	CraftingRequirements *interface{}
}

// ReadFrom reads the data from the reader.
func (p *RecipeBookAddEntriesEntryRecipe) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var displayId pk.VarInt
	temp, err = displayId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.DisplayId = int32(displayId)

	// TODO: Read Display (unsupported type RecipeDisplay)

	// TODO: Read Group (optvarint)

	// TODO: Read Category

	// TODO: Read optional complex type

	return n, nil
}

// WriteTo writes the data to the writer.
func (p RecipeBookAddEntriesEntryRecipe) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.DisplayId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Display (unsupported type RecipeDisplay)

	// TODO: Write Group (optvarint)

	// TODO: Write Category

	// TODO: Write optional complex type

	return n, nil
}

// RecipeBookAddEntriesEntry is a sub-structure used in the packet.
type RecipeBookAddEntriesEntry struct {
	Recipe RecipeBookAddEntriesEntryRecipe
	// TODO: Implement bitflags type
	Flags interface{}
}

// ReadFrom reads the data from the reader.
func (p *RecipeBookAddEntriesEntry) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = p.Recipe.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Read Flags

	return n, nil
}

// WriteTo writes the data to the writer.
func (p RecipeBookAddEntriesEntry) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = p.Recipe.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Flags

	return n, nil
}

// RecipeBookAdd represents the Clientbound RecipeBookAdd packet.

type RecipeBookAdd struct {
	Entries []RecipeBookAddEntriesEntry
	Replace bool
}

// PacketID returns the packet ID for this packet.
func (*RecipeBookAdd) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundRecipeBookAdd
}

// ReadFrom reads the packet data from the reader.
func (p *RecipeBookAdd) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var entriesCount pk.VarInt
	temp, err = entriesCount.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Entries = make([]RecipeBookAddEntriesEntry, entriesCount)
	for i := 0; i < int(entriesCount); i++ {
		temp, err = p.Entries[i].ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}

	var replace pk.Boolean
	temp, err = replace.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Replace = bool(replace)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p RecipeBookAdd) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(len(p.Entries)).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	for i := range p.Entries {
		temp, err = p.Entries[i].WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	temp, err = pk.Boolean(p.Replace).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundRecipeBookAdd, func() ClientboundPacket {
		return &RecipeBookAdd{}
	})
}
