// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// HideMessage represents the Clientbound HideMessage packet.

type HideMessage struct {
	Id int32 `mc:"VarInt"`
	// Optional，當 Id 符合條件時出現
	Signature *[]byte
}

// PacketID returns the packet ID for this packet.
func (*HideMessage) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundHideMessage
}

// ReadFrom reads the packet data from the reader.
func (p *HideMessage) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var id pk.VarInt
	temp, err = id.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Id = int32(id)

	// 當 Id == 0 時讀取 Signature
	if p.Id == 0 {
		var val []byte
		temp, err = (*pk.ByteArray)(&val).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.Signature = &val
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p HideMessage) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.Id).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	if p.Signature != nil {
		temp, err = pk.ByteArray(*p.Signature).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundHideMessage, func() ClientboundPacket {
		return &HideMessage{}
	})
}
