// Code generated by enhanced-generator; DO NOT EDIT.
package client

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type SetTitleText struct {
	Text pk.NBTField
}

func (*SetTitleText) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPacketID(107)
}

// ReadFrom is a stub (not implemented)
func (p *SetTitleText) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p SetTitleText) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ClientboundPacketID(107), func() ClientboundPacket { return &SetTitleText{} })
}
