// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// WorldEvent represents the Clientbound WorldEvent packet.

type WorldEvent struct {
	EffectId int32
	Location pk.Position
	Data     int32
	Global   bool
}

// PacketID returns the packet ID for this packet.
func (*WorldEvent) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundWorldEvent
}

// ReadFrom reads the packet data from the reader.
func (p *WorldEvent) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = (*pk.Int)(&p.EffectId).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Position)(&p.Location).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Int)(&p.Data).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var global pk.Boolean
	temp, err = global.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Global = bool(global)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p WorldEvent) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.Int(p.EffectId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = p.Location.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Int(p.Data).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Boolean(p.Global).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundWorldEvent, func() ClientboundPacket {
		return &WorldEvent{}
	})
}
