// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// WorldBorderLerpSize represents the Clientbound WorldBorderLerpSize packet.

type WorldBorderLerpSize struct {
	OldDiameter float64
	NewDiameter float64
	Speed       int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*WorldBorderLerpSize) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundWorldBorderLerpSize
}

// ReadFrom reads the packet data from the reader.
func (p *WorldBorderLerpSize) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	temp, err = (*pk.Double)(&s.OldDiameter).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = (*pk.Double)(&s.NewDiameter).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	var speed pk.VarInt
	temp, err = speed.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Speed = int32(speed)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p WorldBorderLerpSize) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.Double(p.OldDiameter).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.Double(p.NewDiameter).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(p.Speed).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundWorldBorderLerpSize, func() ClientboundPacket {
		return &WorldBorderLerpSize{}
	})
}
