// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// DeclareRecipesRecipesEntry is a sub-structure used in the packet.
type DeclareRecipesRecipesEntry struct {
	Name  string `mc:"String"`
	Items []int32
}

// ReadFrom reads the data from the reader.
func (p *DeclareRecipesRecipesEntry) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var name pk.String
	temp, err = name.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Name = string(name)

	var itemsCount pk.VarInt
	temp, err = itemsCount.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Items = make([]int32, itemsCount)
	for i := 0; i < int(itemsCount); i++ {
		var elem pk.VarInt
		temp, err = elem.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		p.Items[i] = int32(elem)
	}

	return n, nil
}

// WriteTo writes the data to the writer.
func (p DeclareRecipesRecipesEntry) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.String(p.Name).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(len(p.Items)).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	for i := range p.Items {
		temp, err = pk.VarInt(p.Items[i]).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

// DeclareRecipesStoneCutterRecipesEntry is a sub-structure used in the packet.
type DeclareRecipesStoneCutterRecipesEntry struct {
	Input       interface{}
	SlotDisplay interface{}
}

// ReadFrom reads the data from the reader.
func (p *DeclareRecipesStoneCutterRecipesEntry) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Read Input (unsupported type IDSet)

	// TODO: Read SlotDisplay (unsupported type SlotDisplay)

	return n, nil
}

// WriteTo writes the data to the writer.
func (p DeclareRecipesStoneCutterRecipesEntry) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Write Input (unsupported type IDSet)

	// TODO: Write SlotDisplay (unsupported type SlotDisplay)

	return n, nil
}

// DeclareRecipes represents the Clientbound DeclareRecipes packet.

type DeclareRecipes struct {
	Recipes            []DeclareRecipesRecipesEntry
	StoneCutterRecipes []DeclareRecipesStoneCutterRecipesEntry
}

// PacketID returns the packet ID for this packet.
func (*DeclareRecipes) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundDeclareRecipes
}

// ReadFrom reads the packet data from the reader.
func (p *DeclareRecipes) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var recipesCount pk.VarInt
	temp, err = recipesCount.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Recipes = make([]DeclareRecipesRecipesEntry, recipesCount)
	for i := 0; i < int(recipesCount); i++ {
		temp, err = p.Recipes[i].ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}

	var stoneCutterRecipesCount pk.VarInt
	temp, err = stoneCutterRecipesCount.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.StoneCutterRecipes = make([]DeclareRecipesStoneCutterRecipesEntry, stoneCutterRecipesCount)
	for i := 0; i < int(stoneCutterRecipesCount); i++ {
		temp, err = p.StoneCutterRecipes[i].ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p DeclareRecipes) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(len(p.Recipes)).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	for i := range p.Recipes {
		temp, err = p.Recipes[i].WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	temp, err = pk.VarInt(len(p.StoneCutterRecipes)).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	for i := range p.StoneCutterRecipes {
		temp, err = p.StoneCutterRecipes[i].WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundDeclareRecipes, func() ClientboundPacket {
		return &DeclareRecipes{}
	})
}
