// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"fmt"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// Teams represents the Clientbound Teams packet.

type Teams struct {
	Team string `mc:"String"`
	// TODO: Implement mapper type
	Mode interface{}
	// Switch 基於 Mode：
	//   add -> [array map[countType:varint type:string]]
	//   join -> [array map[countType:varint type:string]]
	//   leave -> [array map[countType:varint type:string]]
	//   default -> void
	Players interface{}
}

// PacketID returns the packet ID for this packet.
func (*Teams) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundTeams
}

// ReadFrom reads the packet data from the reader.
func (p *Teams) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var team pk.String
	temp, err = team.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Team = string(team)

	// TODO: Read Mode

	switch p.Mode {
	default:
		// 無對應負載
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Teams) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.String(p.Team).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	// TODO: Write Mode

	switch v := p.Players.(type) {
	default:
		return n, fmt.Errorf("unsupported switch type for Players: %T", v)
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundTeams, func() ClientboundPacket {
		return &Teams{}
	})
}
