// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// WindowItems represents the Clientbound WindowItems packet.

type WindowItems struct {
	WindowId    int8
	StateId     int32 `mc:"VarInt"`
	Items       []pk.Slot
	CarriedItem pk.Slot
}

// PacketID returns the packet ID for this packet.
func (*WindowItems) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundWindowItems
}

// ReadFrom reads the packet data from the reader.
func (p *WindowItems) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	// TODO: Read WindowId (ContainerID)

	var stateId pk.VarInt
	temp, err = stateId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.StateId = int32(stateId)

	var itemsCount pk.VarInt
	temp, err = itemsCount.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	s.Items = make([]pk.Slot, itemsCount)
	for i := 0; i < int(itemsCount); i++ {
		temp, err = (*pk.Slot)(&s.Items[i]).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}

	temp, err = (*pk.Slot)(&s.CarriedItem).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p WindowItems) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	// TODO: Write WindowId (ContainerID)

	temp, err = pk.VarInt(p.StateId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.VarInt(len(p.Items)).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	for i := range p.Items {
		temp, err = s.Items[i].WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}

	temp, err = s.CarriedItem.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundWindowItems, func() ClientboundPacket {
		return &WindowItems{}
	})
}
