// Code generated by enhanced-generator; DO NOT EDIT.
package client

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type Login struct {
	EntityId            int32 `mc:"Int"`
	IsHardcore          bool  `mc:"Boolean"`
	WorldNames          []interface{}
	MaxPlayers          int32 `mc:"VarInt"`
	ViewDistance        int32 `mc:"VarInt"`
	SimulationDistance  int32 `mc:"VarInt"`
	ReducedDebugInfo    bool  `mc:"Boolean"`
	EnableRespawnScreen bool  `mc:"Boolean"`
	DoLimitedCrafting   bool  `mc:"Boolean"`
	WorldState          interface{}
	EnforcesSecureChat  bool `mc:"Boolean"`
}

func (*Login) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPacketID(43)
}

// ReadFrom is a stub (not implemented)
func (p *Login) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p Login) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ClientboundPacketID(43), func() ClientboundPacket { return &Login{} })
}
