// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"fmt"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)


// Difficulty represents the Clientbound Difficulty packet.

type Difficulty struct {
	// Mapper to string
	Difficulty string
	DifficultyLocked bool
}

// PacketID returns the packet ID for this packet.
func (*Difficulty) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundDifficulty
}


// ReadFrom reads the packet data from the reader.
func (p *Difficulty) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var mapperVal pk.VarInt
	temp, err = mapperVal.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	switch mapperVal {
	case 0:
		p.Difficulty = "peaceful"
	case 1:
		p.Difficulty = "easy"
	case 2:
		p.Difficulty = "normal"
	case 3:
		p.Difficulty = "hard"
	default:
		return n, fmt.Errorf("unknown mapper value %d for Difficulty", mapperVal)
	}

	var difficultyLocked pk.Boolean
	temp, err = difficultyLocked.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	p.DifficultyLocked = bool(difficultyLocked)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Difficulty) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	switch p.Difficulty {
	case "peaceful":
		temp, err = pk.VarInt(0).WriteTo(w)
		n += temp
		if err != nil { return n, err }
	case "easy":
		temp, err = pk.VarInt(1).WriteTo(w)
		n += temp
		if err != nil { return n, err }
	case "normal":
		temp, err = pk.VarInt(2).WriteTo(w)
		n += temp
		if err != nil { return n, err }
	case "hard":
		temp, err = pk.VarInt(3).WriteTo(w)
		n += temp
		if err != nil { return n, err }
	default:
		return n, fmt.Errorf("unknown Difficulty value %v", p.Difficulty)
	}

	temp, err = pk.Boolean(p.DifficultyLocked).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundDifficulty, func() ClientboundPacket {
		return &Difficulty{}
	})
}

