// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// KeepAlive represents the Clientbound KeepAlive packet.

type KeepAlive struct {
	KeepAliveId int64
}

// PacketID returns the packet ID for this packet.
func (*KeepAlive) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundKeepAlive
}

// ReadFrom reads the packet data from the reader.
func (p *KeepAlive) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	temp, err = (*pk.Long)(&s.KeepAliveId).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p KeepAlive) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.Long(p.KeepAliveId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundKeepAlive, func() ClientboundPacket {
		return &KeepAlive{}
	})
}
