// Code generated by enhanced-generator; DO NOT EDIT.
package client

import (
	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"io"
)

// keep pk import used even when no pk.* fields are present
var _ = pk.Angle(0)

type RelEntityMove struct {
	EntityId int32 `mc:"VarInt"`
	DX       int16 `mc:"Short"`
	DY       int16 `mc:"Short"`
	DZ       int16 `mc:"Short"`
	OnGround bool  `mc:"Boolean"`
}

func (*RelEntityMove) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundPacketID(0)
}

// ReadFrom is a stub (not implemented)
func (p *RelEntityMove) ReadFrom(r io.Reader) (n int64, err error) { return 0, nil }

// WriteTo is a stub (not implemented)
func (p RelEntityMove) WriteTo(w io.Writer) (n int64, err error) { return 0, nil }

func init() {
	registerPacket(packetid.ClientboundPacketID(0), func() ClientboundPacket { return &RelEntityMove{} })
}
