// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// Animation represents the Clientbound Animation packet.

type Animation struct {
	EntityId  int32 `mc:"VarInt"`
	Animation uint8
}

// PacketID returns the packet ID for this packet.
func (*Animation) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundAnimation
}

// ReadFrom reads the packet data from the reader.
func (p *Animation) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var entityId pk.VarInt
	temp, err = entityId.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.EntityId = int32(entityId)

	var animation pk.UnsignedByte
	temp, err = animation.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.Animation = uint8(animation)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Animation) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.EntityId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	temp, err = pk.UnsignedByte(p.Animation).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundAnimation, func() ClientboundPacket {
		return &Animation{}
	})
}
