// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"io"

	"git.konjactw.dev/falloutBot/go-mc/data/packetid"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)

// TrackedWaypointWaypointIcon is a sub-structure used in the packet.
type TrackedWaypointWaypointIcon struct {
	Style string `mc:"String"`
	Color *int32
}


// ReadFrom reads the data from the reader.
func (s *TrackedWaypointWaypointIcon) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var style pk.String
	temp, err = style.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	s.Style = string(style)

	var hasColor pk.Boolean
	temp, err = hasColor.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	if hasColor {
		var val int32
		temp, err = (*pk.i32)(&val).ReadFrom(r)
		n += temp
		if err != nil { return n, err }
		s.Color = &val
	}

	return n, nil
}

// WriteTo writes the data to the writer.
func (s TrackedWaypointWaypointIcon) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.String(p.Style).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	if p.Color != nil {
		temp, err = pk.Boolean(true).WriteTo(w)
		n += temp
		if err != nil { return n, err }
		temp, err = s.Color.WriteTo(w)
		n += temp
		if err != nil { return n, err }
	} else {
		temp, err = pk.Boolean(false).WriteTo(w)
		n += temp
		if err != nil { return n, err }
	}

	return n, nil
}


// TrackedWaypointWaypoint is a sub-structure used in the packet.
type TrackedWaypointWaypoint struct {
	HasUUID bool
	// TODO: Switch type - conditional field based on other field value
	 interface{}
	Icon TrackedWaypointWaypointIcon
	// TODO: Implement mapper type
	Type interface{}
	// TODO: Switch type - conditional field based on other field value
	Data interface{}
}


// ReadFrom reads the data from the reader.
func (s *TrackedWaypointWaypoint) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	var hasUUID pk.Boolean
	temp, err = hasUUID.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	s.HasUUID = bool(hasUUID)

	// TODO: Implement switch field read

	temp, err = s.Icon.ReadFrom(r)
	n += temp
	if err != nil { return n, err }

	// TODO: Read Type

	// TODO: Implement switch field read

	return n, nil
}

// WriteTo writes the data to the writer.
func (s TrackedWaypointWaypoint) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	temp, err = pk.Boolean(p.HasUUID).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	// TODO: Implement switch field write

	temp, err = s.Icon.WriteTo(w)
	n += temp
	if err != nil { return n, err }

	// TODO: Write Type

	// TODO: Implement switch field write

	return n, nil
}



// TrackedWaypoint represents the Clientbound TrackedWaypoint packet.

type TrackedWaypoint struct {
	// TODO: Implement mapper type
	Operation interface{}
	Waypoint TrackedWaypointWaypoint
}

// PacketID returns the packet ID for this packet.
func (*TrackedWaypoint) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundTrackedWaypoint
}


// ReadFrom reads the packet data from the reader.
func (p *TrackedWaypoint) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64

	// TODO: Read Operation

	temp, err = s.Waypoint.ReadFrom(r)
	n += temp
	if err != nil { return n, err }

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p TrackedWaypoint) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64

	// TODO: Write Operation

	temp, err = s.Waypoint.WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundTrackedWaypoint, func() ClientboundPacket {
		return &TrackedWaypoint{}
	})
}

