// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
)


// Camera represents the Clientbound Camera packet.

type Camera struct {
	CameraId int32 `mc:"VarInt"`
}

// PacketID returns the packet ID for this packet.
func (*Camera) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundCamera
}


// ReadFrom reads the packet data from the reader.
func (p *Camera) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	var cameraId pk.VarInt
	temp, err = cameraId.ReadFrom(r)
	n += temp
	if err != nil { return n, err }
	p.CameraId = int32(cameraId)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Camera) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	temp, err = pk.VarInt(p.CameraId).WriteTo(w)
	n += temp
	if err != nil { return n, err }

	return n, nil
}


func init() {
	registerPacket(packetid.ClientboundCamera, func() ClientboundPacket {
		return &Camera{}
	})
}

