// Code generated by enhanced-generator v2 from protocol.json; DO NOT EDIT manually.
// To regenerate: go run main_v2.go -protocol <path> -output <dir> -direction client

package client

import (
	pk "git.konjactw.dev/falloutBot/go-mc/net/packet"
	"git.konjactw.dev/patyhank/minego/pkg/protocol/packetid"
	"io"
)

// Respawn represents the Clientbound Respawn packet.

type Respawn struct {
	WorldState   interface{}
	CopyMetadata uint8
}

// PacketID returns the packet ID for this packet.
func (*Respawn) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundRespawn
}

// ReadFrom reads the packet data from the reader.
func (p *Respawn) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Read WorldState (unsupported type SpawnInfo)

	var copyMetadata pk.UnsignedByte
	temp, err = copyMetadata.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	p.CopyMetadata = uint8(copyMetadata)

	return n, nil
}

// WriteTo writes the packet data to the writer.
func (p Respawn) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	_ = temp

	// TODO: Write WorldState (unsupported type SpawnInfo)

	temp, err = pk.UnsignedByte(p.CopyMetadata).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}

	return n, nil
}

func init() {
	registerPacket(packetid.ClientboundRespawn, func() ClientboundPacket {
		return &Respawn{}
	})
}
